### ISSUE TITLE
Enzyme + linguiJS v3 error 

### ISSUE THREAD

**Issue by Skippidar** [lingui/js-lingui#1005]
**Describe the bug**
Using v3 linguiJS with enzyme for testing results in error 'useLingui hook was used without I18nProvider'

**To Reproduce**
Test any component with ```<Trans>``` or any other component\macros

```
import React from 'react';
import Pagination, { Pager } from '../../src/components/pagination';

const getType = (e) => {
    const modifier = e.props().modifier;
    return (modifier === 'hide--below-tablet' && 'd') // PC only
        || (modifier === 'hide--above-desktop' && 't') // mobile only
        || 'a'; // all resolutions
};

describe('test.pagination.spec.jsx', () => {
    it('should render 14page', () => {
        const props = {
            total: 14,
            current: 1,
            pageSize: 1,
            onChange: () => {},
        };
        const component = mount(<Pagination {...props} />);
        let element = component.find(Pager);
        expect(element.map(e => e.props().page)).to.eql([1, 2, 3, 4, 5, 6, 7, 'next', 14]);
        expect(element.map(getType)).to.eql(['a', 'a', 'a', 'a', 'a', 'd', 'd', 'a', 'a']);
    });
});
```
Run tests and get error 
```
Error: useLingui hook was used without I18nProvider.
    at useLingui (./node_modules/@lingui/react/cjs/react.development.js:21:13)
    at Trans (./node_modules/@lingui/react/cjs/react.development.js:246:20)
    at renderWithHooks (./node_modules/react-dom/cjs/react-dom.development.js:14985:18)
    at mountIndeterminateComponent (./node_modules/react-dom/cjs/react-dom.development.js:17811:13)
```
And tests fail because initial strings result in empty strings after component was rendered.

Enzyme environment setup:
```
import { JSDOM } from 'jsdom';
import { mount, render, shallow, configure } from 'enzyme';
import Adapter from '@wojtekmaj/enzyme-adapter-react-17';
import { expect } from 'chai';

configure({ adapter: new Adapter() });

global.expect = expect;
global.mount = mount;
global.render = render;
global.shallow = shallow;

const { window } = new JSDOM('<!doctype html><html><body></body></html>');

function copyProps(src, target) {
    const props = Object.getOwnPropertyNames(src)
        .filter(prop => typeof target[prop] === 'undefined')
        .reduce((result, prop) => ({
            ...result,
            [prop]: Object.getOwnPropertyDescriptor(src, prop),
        }), {});
    Object.defineProperties(target, props);
}

global.window = window;
global.window.__webpack_hash__ = window.__webpack_hash__;
global.document = window.document;
// eslint-disable-next-line func-names
global.window.matchMedia = window.matchMedia || function () {
    return {
        matches: true,
        addListener() {},
        removeListener() {},
    };
};
// eslint-disable-next-line func-names
global.window.getComputedStyle = window.getComputedStyle || function () {
    return {
        getComputedStyle() {},
    };
};
global.navigator = {
    userAgent: 'node.js',
};

copyProps(window, global);
```

**Expected behavior**
Tests pass (with v2 everything is ok)

**Comment by semoal** [comment]
You need to wrap your <Pagination component with <I18nProvider /> the error is self-explanatory.
You can check the source code of Lingui where we have tests with jest wrapping our jsx components with I18nProvider.
