### ISSUE TITLE
if the message has curly brackets in itself, compilation is broken

### ISSUE THREAD

**Issue by capaj** [lingui/js-lingui#1075]
**Describe the bug**
if the message has curly brackets in itself, compilation is broken

**To Reproduce**

```
import { t } from "@lingui/macro"

t`curly brackets { } in a message break compilation.`
```
extract and try to compile

**Expected behavior**
compilation works fine
**Additional context**
message format

```
/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/compile.js:89
    throw new Error("Can't parse message. Please check correct syntax: \"".concat(message, "\" \n \n Messageformat-parser trace: ").concat(e.message));
    ^

Error: Can't parse message. Please check correct syntax: "The strings contains invalid variable definition.Please ensure the number of variables matches the number used in the original string. A variable is enclosed in curly brackets { }." 
 
 Messageformat-parser trace: Expected identifier but "}" found.
    at compile (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/compile.js:89:11)
    at /home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/compile.js:45:51
    at Array.map (<anonymous>)
    at createCompiledCatalog (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/compile.js:37:43)
    at /home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/lingui-compile.js:91:66
    at Array.forEach (<anonymous>)
    at /home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/lingui-compile.js:61:14
    at Array.forEach (<anonymous>)
    at command (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/lingui-compile.js:50:18)
    at compile (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/lingui-compile.js:135:12)
```

- jsLingui version ``lingui --version`` 3.8.10
- Babel version ``npm list @babel/core`` 7.14.0
- Your Babel config (e.g. `.babelrc`) not relevant

**Comment by semoal** [comment]
Yeah this is an error itself from the `message-format` parser dependency we have in the cli, there's also an issue with Vietnamese support which is fixed in the new package. #1033 

I'll try to find time as soon as possible to migrate to this new parser which probably fixes all this situations where we don't have any control :/
