### ISSUE TITLE
TypeError: macro_1.t is not a function

### ISSUE THREAD

**Issue by kopax-polyconseil** [lingui/js-lingui#1092]
**Describe the bug**

Hi everyone, I am trying to understand how to configure the macro properly as it seems the documentation example does not work in an ejected created react app imported in our project.

When running `yarn test:unit:web`, we are having this error:

**To Reproduce**

```
git clone https://github.com/pass-culture/pass-culture-app-native.git
cd pass-culture-app-native
git checkout jest-web
yarn --force
yarn test:unit:web
```

**Expected behavior**

I expect lingui macro to be defined

**Additional context**

We have this application running and configured in react-native. We are now trying to use the same code base to build a Web Application, this error only happen when running test for the web. (in comparaison with `yarn test:unit`)

- jsLingui version 3.9.0
- Babel version  7.8.4
- Your Babel config [`babel.config.js`](https://github.com/pass-culture/pass-culture-app-native/blob/jest-web/babel.config.js) and [`webpack.config.js`](https://github.com/pass-culture/pass-culture-app-native/blob/jest-web/web/config/webpack.config.js#L365)

**Comment by kopax-polyconseil** [comment]
I have created a `babel.config.web.js` for ts-loader and I try to fix it that way, this is how the file look like:

```
module.exports = {
  presets: ['@babel/preset-env', '@babel/preset-react', '@babel/preset-typescript'],
  plugins: [
    'macros',
    '@babel/proposal-class-properties',
    [
      require.resolve('babel-plugin-module-resolver'),
      {
        cwd: 'babelrc',
        extensions: ['.js', '.jsx', '.ts', '.tsx', '.js'],
        root: ['./src/'],
        alias: {
          api: './src/api',
          features: './src/features',
          libs: './src/libs',
          locales: './src/locales',
          types: './src/types',
          tests: './src/tests',
          ui: './src/ui',
          __mocks__: './__mocks__',
        },
      },
    ],
  ],
}
```

In `jest.config.web.js`, this is how I configure it:

```diff
  globals: {
    __DEV__: true,
    'ts-jest': {
+      babelConfig: 'babel.config.web.js',
      tsconfig: 'tsconfig.json',
      diagnostics: true,
    },
  },
```

I have now this error:

```bash
    TypeError: /home/dka/workspace/github.com/pass-culture/pass-culture-app-native/src/api/__mocks__/helpers.ts: @lingui/macro: Cannot read property 'findIndex' of undefined Learn more: https://www.npmjs.com/package/@lingui/macro

      at MacroJs.processDescriptor (node_modules/@lingui/macro/macroJs.js:151:48)
      at MacroJs.replaceTAsFunction (node_modules/@lingui/macro/macroJs.js:142:30)
      at MacroJs.replacePath (node_modules/@lingui/macro/macroJs.js:109:15)
      at node_modules/@lingui/macro/index.js:82:11
          at Array.forEach (<anonymous>)
      at macro (node_modules/@lingui/macro/index.js:77:39)
      at macroWrapper (node_modules/babel-plugin-macros/dist/index.js:63:12)
      at applyMacros (node_modules/babel-plugin-macros/dist/index.js:230:14)
      at ImportDeclaration (node_modules/babel-plugin-macros/dist/index.js:114:28)
      at NodePath._call (node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:55:20)

```

I have no clue on which error is best, it seems like this error is at least going into the babel plugin macros and lingui macro.

**Comment by kopax-polyconseil** [comment]
I solved it by not using ts-jest but babel-jest with:

```
  transform: {
    '^.+\\.[jt]sx?$': 'babel-jest',
  },
```

As explained in jest configuration.
