### ISSUE TITLE
 @lingui/macro: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but instead got "TSFunctionType"

### ISSUE THREAD

**Issue by cameronbraid** [lingui/js-lingui#1145]
**Describe the bug**

```
Module build failed (from ./node_modules/gatsby/dist/utils/babel-loader.js):
TypeError: /workspace/octane/src/turbo2/js/TurboBookModel.ts: @lingui/macro: Property value of ObjectProperty expected node to be of a type ["Expression","PatternLike"] but
instead got "TSFunctionType" Learn more: https://www.npmjs.com/package/@lingui/macro
    at Object.validate (/workspace/octane/node_modules/@babel/core/node_modules/@babel/types/lib/definitions/utils.js:130:11)
    at validateField (/workspace/octane/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:24:9)
    at validate (/workspace/octane/node_modules/@babel/core/node_modules/@babel/types/lib/validators/validate.js:17:3)
    at builder (/workspace/octane/node_modules/@babel/core/node_modules/@babel/types/lib/builders/builder.js:38:27)
    at Object.objectProperty (/workspace/octane/node_modules/@babel/core/node_modules/@babel/types/lib/builders/generated/index.js:400:31)
    at /workspace/octane/node_modules/@lingui/macro/macroJs.js:81:30
    at Array.map (<anonymous>)
    at MacroJs.replacePathWithMessage (/workspace/octane/node_modules/@lingui/macro/macroJs.js:80:48)
    at MacroJs.replacePath (/workspace/octane/node_modules/@lingui/macro/macroJs.js:162:13)
    at /workspace/octane/node_modules/@lingui/macro/index.js:83:15
    at Array.forEach (<anonymous>)
    at macro (/workspace/octane/node_modules/@lingui/macro/index.js:78:39)
    at macroWrapper (/workspace/octane/node_modules/babel-plugin-macros/dist/index.js:57:12)
    at applyMacros (/workspace/octane/node_modules/babel-plugin-macros/dist/index.js:226:14)
    at ImportDeclaration (/workspace/octane/node_modules/babel-plugin-macros/dist/index.js:110:28)
    at NodePath._call (/workspace/octane/node_modules/@babel/core/node_modules/@babel/traverse/lib/path/context.js:53:20)
```

**To Reproduce**
Not sure, just happened when I added a new function to a class I was working on.

- jsLingui version :
```
    "@lingui/cli": "^3.12.1",
    "@lingui/detect-locale": "^3.12.1",
    "@lingui/macro": "^3.12.1",
    "@lingui/react": "^3.12.1",
```
- Babel version 
```
@drivenow/octane@1.0.0 /workspace/octane
├── @babel/core@7.15.5 
├─┬ @compiled/babel-plugin@0.6.14
│ └── @babel/core@7.15.0 
├─┬ @mdx-js/mdx@1.6.22
│ ├── @babel/core@7.12.9 
│ └─┬ remark-mdx@1.6.22
│   └── @babel/core@7.12.9 
├─┬ @playwright/test@1.15.1
│ └── @babel/core@7.15.5  deduped
├─┬ @svgr/webpack@5.5.0
│ ├── @babel/core@7.15.0 
│ └─┬ @svgr/plugin-jsx@5.5.0
│   └── @babel/core@7.15.0 
├─┬ babel-jest@27.2.4
│ ├─┬ @jest/transform@27.2.4
│ │ └── @babel/core@7.15.0 
│ └─┬ babel-plugin-istanbul@6.0.0
│   └─┬ istanbul-lib-instrument@4.0.3
│     └── @babel/core@7.15.0 
├─┬ fetch-mock@9.11.0
│ └── @babel/core@7.15.0 
├─┬ gatsby-plugin-graphql-codegen@3.0.0
│ └─┬ @graphql-codegen/typescript@1.23.0
│   └─┬ @graphql-codegen/visitor-plugin-common@1.22.0
│     └─┬ @graphql-tools/relay-operation-optimizer@6.3.4
│       └─┬ relay-compiler@11.0.2
│         └── @babel/core@7.15.0 
├─┬ gatsby-plugin-mdx@2.14.0
│ └── @babel/core@7.15.5  deduped
├─┬ gatsby-plugin-ts-config@2.1.2
│ └── @babel/core@7.15.5  deduped
├─┬ gatsby-plugin-typescript@3.14.0
│ └── @babel/core@7.15.5  deduped
├─┬ jest@27.2.4
│ └─┬ @jest/core@27.2.4
│   ├─┬ jest-config@27.2.4
│   │ └── @babel/core@7.15.0 
│   └─┬ jest-snapshot@27.2.4
│     └── @babel/core@7.15.5  deduped
└─┬ stylelint@13.13.1
  └─┬ @stylelint/postcss-css-in-js@0.37.2
    └── @babel/core@7.15.0 
```
- Your Babel config (e.g. `.babelrc`) or framework you use `gatsby`

**Comment by mdtusz** [comment]
Has this been resolved in a release? I'm encountering this issue as well and the line that seems to be causing the error is this:

```ts
type TabUpdate = (t: Tab) => Tab;
```

I'm guessing it has to do with an issue in parsing this typescript syntax for defining function signatures?
