### ISSUE TITLE
error: Error: Unable to resolve module @lingui/macro

### ISSUE THREAD

**Issue by JoyCood** [lingui/js-lingui#1307]
when run **yarn extract** command is ok, but when run **npx react-native run-android** throw bellow error.  help me please, thank you!
```
error: Error: Unable to resolve module @lingui/macro from H:\projects\AwesomeTSProject\src\App.tsx: @lingui/macro could not be found within the project or in these directories:
  node_modules
  25 | import { messages } from './locales/en-US/messages';
  26 |
> 27 | import { Trans } from '@lingui/macro';
     |                        ^
  28 |
  29 | i18n.load('en', messages);
  30 | i18n.activate('en')
    at ModuleResolver.resolveDependency (H:\projects\AwesomeTSProject\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:178:15)
    at DependencyGraph.resolveDependency (H:\projects\AwesomeTSProject\node_modules\metro\src\node-haste\DependencyGraph.js:264:43)
    at Object.resolve (H:\projects\AwesomeTSProject\node_modules\metro\src\lib\transformHelpers.js:170:21)
    at resolveDependencies (H:\projects\AwesomeTSProject\node_modules\metro\src\DeltaBundler\graphOperations.js:466:33)
    at processModule (H:\projects\AwesomeTSProject\node_modules\metro\src\DeltaBundler\graphOperations.js:232:31)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async traverseDependenciesForSingleFile (H:\projects\AwesomeTSProject\node_modules\metro\src\DeltaBundler\graphOperations.js:221:3)
    at async traverseDependencies (H:\projects\AwesomeTSProject\node_modules\metro\src\DeltaBundler\graphOperations.js:147:7)
    at async DeltaCalculator._getChangedDependencies (H:\projects\AwesomeTSProject\node_modules\metro\src\DeltaBundler\DeltaCalculator.js:263:42)
```

package.json
```
{
  "name": "awesometsproject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint . --ext .js,.jsx,.ts,.tsx",
    "extract": "lingui extract --clean",
    "compile": "lingui compile  --strict"
  },
  "dependencies": {
    "@lingui/react": "^3.15.0",
    "react": "18.1.0",
    "react-native": "0.70.6"
  },
  "devDependencies": {
    "@babel/core": "^7.12.9",
    "@babel/runtime": "^7.12.5",
    "@lingui/cli": "^3.15.0",
    "@lingui/macro": "^3.15.0",
    "@react-native-community/eslint-config": "^2.0.0",
    "@tsconfig/react-native": "^2.0.2",
    "@types/jest": "^26.0.23",
    "@types/react": "^18.0.21",
    "@types/react-native": "^0.70.6",
    "@types/react-test-renderer": "^18.0.0",
    "@typescript-eslint/eslint-plugin": "^5.37.0",
    "@typescript-eslint/parser": "^5.37.0",
    "babel-jest": "^26.6.3",
    "babel-plugin-macros": "^3.1.0",
    "eslint": "^7.32.0",
    "jest": "^26.6.3",
    "metro-react-native-babel-preset": "0.72.3",
    "react-test-renderer": "18.1.0",
    "typescript": "^4.8.3"
  },
  "jest": {
    "preset": "react-native",
    "moduleFileExtensions": [
      "ts",
      "tsx",
      "js",
      "jsx",
      "json",
      "node"
    ]
  }
}
```

lingui.config.ts
```
const linguiConfig = {
  catalogs: [
    {
      path: '<rootDir>/src/locales/{locale}/messages',
      include: ['<rootDir>/src'],
    },
  ],
  compileNamespace: 'cjs',
  fallbackLocales: {
    default: 'en-US',
  },
  format: 'po',
  formatOptions: {
    lineNumbers: false,
  },
  locales: [
    'en-US',
    'zh-CN',
  ],
  orderBy: 'messageId',
  rootDir: '.',
  runtimeConfigModule: ['@lingui/core', 'i18n'],
  sourceLocale: 'en-US',
  pseudoLocale: 'pseudo',
}

export default linguiConfig
```

App.js
``` 
import React from 'react';
import {
	SafeAreaView,
	StatusBar,
	useColorScheme,
	View,
} from 'react-native';

import {
	Colors,
} from 'react-native/Libraries/NewAppScreen';

import { i18n } from '@lingui/core';
import { I18nProvider } from '@lingui/react';
import { messages } from './locales/en-US/messages';

import { Trans } from '@lingui/macro';

i18n.load('en', messages);
i18n.activate('en')

const App = () => {
	const isDarkMode = useColorScheme() === 'dark';

	const backgroundStyle = {
		backgroundColor: isDarkMode ? Colors.darker : Colors.lighter,
	};

	return (
		<I18nProvider i18n={i18n}>
			<SafeAreaView style={backgroundStyle}>
				<StatusBar
					barStyle={isDarkMode ? 'light-content' : 'dark-content'}
					backgroundColor={backgroundStyle.backgroundColor}
				/>
				<View>
					<h1><Trans>Hello linguiJS</Trans></h1>
				</View>
			</SafeAreaView>
		</I18nProvider>
	);
};

export default App;```

**Comment by thekip** [comment]
`@lingui/macro` is using babel macro plugin. Which should be installed. Follow the documentation for more info https://lingui.js.org/ref/macro.html
