### ISSUE TITLE
[v4 bug] Unable to extract message wrapped within another function call 

### ISSUE THREAD

**Issue by taozhou-glean** [lingui/js-lingui#1487]
minimal repro case:

```
import { t } from '@lingui/macro';

const msg = message.error(t({message: "dasd"}))
```

error stack:

```
Cannot process file s.tsx s.tsx: @lingui/macro: Cannot read properties of undefined (reading 'find') Learn more: https://www.npmjs.com/package/@lingui/macro
TypeError: s.tsx: @lingui/macro: Cannot read properties of undefined (reading 'find') Learn more: https://www.npmjs.com/package/@lingui/macro
    at MacroJs.getObjectPropertyByKey (node_modules/@lingui/macro/build/macroJs.js:321:33)
    at MacroJs.processDescriptor (xnode_modules/@lingui/macro/build/macroJs.js:153:34)
    at MacroJs.replaceTAsFunction (node_modules/@lingui/macro/build/macroJs.js:129:29)
    at MacroJs.replacePath (node_modules/@lingui/macro/build/macroJs.js:75:12)
```

looks like the descriptor passed to `getObjectPropertyByKey` is `CallExpression` not the argument (`ObjectExpression`)

**Comment by taozhou-glean** [comment]
this works fine in v3

**Comment by leonard-henriquez** [comment]
@thekip @andrii-bodnar , I still get this error with v4.0.0-next.4.
Is it normal ?

```
Cannot process file /project/apps/frontend/component.tsx /project/apps/frontend/component.tsx: @lingui/macro: Cannot read properties of undefined (reading 'find') Learn more: https://www.npmjs.com/package/@lingui/macro
TypeError: /project/apps/frontend/componentp.tsx: @lingui/macro: Cannot read properties of undefined (reading 'find') Learn more: https://www.npmjs.com/package/@lingui/macro
    at MacroJs.getObjectPropertyByKey (/project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:380:33)
    at MacroJs.processDescriptor (/project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:190:36)
    at MacroJs.replaceTAsFunction (/project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:167:31)
    at MacroJs.replacePath (/project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:155:14)
    at /project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:826:16
    at Array.forEach (<anonymous>)
    at macro (/project/node_modules/.pnpm/@lingui+macro@4.0.0-next.4_pq4dv42nqxohbcry6fc5ekvzle/node_modules/@lingui/macro/dist/index.cjs:820:49)
   ...
```

**Comment by leonard-henriquez** [comment]
PS: I can't tell which occurence throwed this error. How can i know which is responsible?

**Comment by taozhou-glean** [comment]
unless you have a lot strings in `/project/apps/frontend/componentp.tsx`, it should be relatively easy to narrow it down to a minimum repro case
