### ISSUE TITLE
Vite and 4: No known conditions for "./api" specifier in "@lingui/cli" package 

### ISSUE THREAD

**Issue by ptmkenny** [lingui/js-lingui#1565]
**Describe the bug/support request**

I'm trying to switch from CRA to Vite in my React app, and I'm getting the following error from lingui:

```
✘ [ERROR] No known conditions for "./api" specifier in "@lingui/cli" package [plugin vite:dep-pre-bundle]

    node_modules/@lingui/macro/dist/index.mjs:4:34:
      4 │ import { generateMessageId } from '@lingui/cli/api';
        ╵                                   ~~~~~~~~~~~~~~~~~

  This error came from the "onResolve" callback registered here:

    node_modules/esbuild/lib/main.js:1279:20:
      1279 │       let promise = setup({
           ╵                     ^

    at setup (file:///Users/private/d/ionic/node_modules/vite/dist/node/chunks/dep-79892de8.js:23569:19)
    at handlePlugins (/Users/private/d/ionic/node_modules/esbuild/lib/main.js:1279:21)
    at buildOrContextImpl (/Users/private/d/ionic/node_modules/esbuild/lib/main.js:968:5)
    at Object.buildOrContext (/Users/private/d/ionic/node_modules/esbuild/lib/main.js:776:5)
    at /Users/private/d/ionic/node_modules/esbuild/lib/main.js:2172:68
    at new Promise (<anonymous>)
    at Object.context (/Users/private/d/ionic/node_modules/esbuild/lib/main.js:2172:27)
    at Object.context (/Users/private/d/ionic/node_modules/esbuild/lib/main.js:2012:58)
    at prepareEsbuildOptimizerRun (file:///Users/private/d/ionic/node_modules/vite/dist/node/chunks/dep-79892de8.js:44840:35)

  vite:resolve 24.99ms react-dom -> /Users/private/d/ionic/node_modules/react-dom/index.js +26ms
  vite:resolve 25.01ms use-sync-external-store/shim/index.js -> /Users/private/d/ionic/node_modules/use-sync-external-store/shim/index.js +0ms
  vite:resolve 25.00ms tiny-warning -> /Users/private/d/ionic/node_modules/tiny-warning/dist/tiny-warning.esm.js +1ms
  vite:resolve 25.01ms @babel/runtime/helpers/possibleConstructorReturn -> /Users/private/d/ionic/node_modules/@babel/runtime/helpers/esm/possibleConstructorReturn.js +0ms
  vite:resolve 7.00ms chalk -> /Users/private/d/ionic/node_modules/@lingui/conf/node_modules/chalk/source/index.js +7ms

```

**To Reproduce**

vite.config.ts (based on [this](https://github.com/lingui/js-lingui/issues/1246#issuecomment-1164089885))

```
import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [react({
    babel: {
      plugins: ['macros'],
    }
  })],
})
```

lingui.config.ts

```
const config = {
  locales: ['en', 'ja'],
  sourceLocale: 'en',
  catalogs: [
    {
      path: 'src/locales/{locale}/messages',
      include: ['src'],
    },
  ],
  compileNamespace: 'ts',
  format: 'po',
  extractBabelOptions: {
    presets:
    ['@babel/preset-typescript']
  }
};

export default config;
```

**Additional context**

- jsLingui version ``lingui --version``
4.0-next4

- Babel version ``npm list @babel/core``

```
├─┬ @babel/eslint-parser@7.21.3
│ └─┬ @babel/core@7.21.3
│   └─┬ @babel/helper-compilation-targets@7.20.7
│     └── @babel/core@7.21.3 deduped
├─┬ @babel/preset-react@7.18.6
│ ├── @babel/core@7.21.3 deduped
│ ├─┬ @babel/plugin-transform-react-display-name@7.18.6
│ │ └── @babel/core@7.21.3 deduped
│ ├─┬ @babel/plugin-transform-react-jsx-development@7.18.6
│ │ └── @babel/core@7.21.3 deduped
│ ├─┬ @babel/plugin-transform-react-jsx@7.21.0
│ │ ├── @babel/core@7.21.3 deduped
│ │ └─┬ @babel/plugin-syntax-jsx@7.18.6
│ │   └── @babel/core@7.21.3 deduped
│ └─┬ @babel/plugin-transform-react-pure-annotations@7.18.6
│   └── @babel/core@7.21.3 deduped
├─┬ @babel/preset-typescript@7.21.0
│ ├── @babel/core@7.21.3 deduped
│ └─┬ @babel/plugin-transform-typescript@7.21.3
│   ├── @babel/core@7.21.3 deduped
│   ├─┬ @babel/helper-create-class-features-plugin@7.21.0
│   │ └── @babel/core@7.21.3 deduped
│   └─┬ @babel/plugin-syntax-typescript@7.20.0
│     └── @babel/core@7.21.3 deduped
├─┬ @lingui/cli@4.0.0-next.4
│ └── @babel/core@7.21.3 deduped
├─┬ @vitejs/plugin-react@3.1.0
│ ├── @babel/core@7.21.3 deduped
│ ├─┬ @babel/plugin-transform-react-jsx-self@7.21.0
│ │ └── @babel/core@7.21.3 deduped
│ └─┬ @babel/plugin-transform-react-jsx-source@7.19.6
│   └── @babel/core@7.21.3 deduped
└─┬ eslint-plugin-flowtype@8.0.3
  └─┬ @babel/plugin-syntax-flow@7.18.6
    └── @babel/core@7.21.3 deduped
```

Any hints about how to fix this would be much appreciated.

**Comment by andrii-bodnar** [comment]
Hi @ptmkenny,

Could you please try our [vite-project-react-babel](https://github.com/lingui/js-lingui/tree/next/examples/vite-project-react-babel) example?

As I can see, your `vite.config.ts` missing the `lingui()` plugin at least. For more detail, see the [Setup with Vite](https://lingui.dev/tutorials/setup-vite) article.
