### ISSUE TITLE
useLingui hook issue when importing a React Component from one application into another

### ISSUE THREAD

**Issue by nagamohanm** [lingui/js-lingui#1571]
I am trying to export a few react components (**ComponentA**, **ComponentB**) that include text surrounded by `<Trans />`  from let's say **Project A**. In **Project B**, I am importing these components as 

```
import { ComponentA, Component B } from '@projectA'
```

What is happening is as long as the code with `<Trans />` surrounding the text is not loaded (say due to some conditions not satisfied), the remaining Component is getting displayed in the UI. But once the conditions are met and the text has to be loaded, I am getting the below error:

```
useLingui hook was used without I18nProvider.
    at useLingui (webpack-internal:///./node_modules/@lingui/react/build/cjs/index.js:11:13)
    at Trans (webpack-internal:///./node_modules/@lingui/react/build/cjs/index.js:187:7)
    at renderWithHooks (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31)
    at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:7)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22155:12)
```

Both **ProjectA** and **ProjectB** have the `<I18nProvider i18n={i18n} />` surrounding the root component in their respective root files.

**Expected behavior**

**Additional context**
This started happening once I upgraded the version from 3.12.0 to 3.15.0

- jsLingui version ``^3.15.0``
- Babel version ``^7.7.7``

.babelrc
```
{
  "presets": [
    "@babel/preset-env",
    "@babel/preset-react"
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-transform-runtime",
    "react-hot-loader/babel",
    "macros"
  ]
}
```

As I am under NDA in the company I am working in, I cannot attach too much info. Kindly let me know what else is required from me, and I will try to share as much as possible.

Thank you in advance for any suggestions/feedback.

**Comment by thekip** [comment]
Problem with your configuration. You most likely have 2  copies of lingui context in your final application bundle. Look here for more context https://github.com/lingui/js-lingui/issues/1500

**Comment by nagamohanm** [comment]
@thekip Thank you for your suggestion. We are trying out the changes as mentioned in the comment. I will update here again on the progress

**Comment by thekip** [comment]
To prove the theory you can inspect your bundle (in browser for example) and search for `@lingui/react` sources. They would be two times there, one as commonjs and second as esm

**Comment by nagamohanm** [comment]
@thekip I checked the bundle using webpack-bundle-analyzer and noticed that the lingui bundle had both esm and cjs folders. I made the following change in **ProjectA's** webpack config externals:

Before:
```
externals: [
    {
      react: 'commonjs2 react',
      'react-dom': 'commonjs2 react-dom'
    },
    /@material-ui\/.*/,
    /@lingui\/.*/
  ]
```
After:
```
externals: [
    {
      react: 'commonjs2 react',
      'react-dom': 'commonjs2 react-dom',
      '@lingui': 'commonjs2 @lingui'
    },
    /@material-ui\/.*/
  ]
```
When I checked again, lingui had only esm folder in ProjectB
<img width="556" alt="image" src="https://user-images.githubusercontent.com/28477401/229477731-266a8013-b035-4f38-a91b-4e74498224d8.png">

But now I am getting another error, which I am debugging:
```
ERROR
Cannot read properties of null (reading 'i18n')
TypeError: Cannot read properties of null (reading 'i18n')
    at h (webpack-internal:///./node_modules/@tt-dclm/dclm-web-ui/dist/js/exports.js:121:6820087)
    at renderWithHooks (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:14804:18)
    at mountIndeterminateComponent (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:17483:13)
    at beginWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:18597:16)
    at HTMLUnknownElement.callCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:189:14)
    at Object.invokeGuardedCallbackDev (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:238:16)
    at invokeGuardedCallback (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:293:31)
    at beginWork$1 (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:23204:7)
    at performUnitOfWork (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22155:12)
    at workLoopSync (webpack-internal:///./node_modules/@hot-loader/react-dom/cjs/react-dom.development.js:22131:22)
```

Thanks for your support ☺️
