### ISSUE TITLE
Experimental Syntax 'importAttributes' Not Enabled

### ISSUE THREAD

**Issue by zvictor** [lingui/js-lingui#1717]
**Description**

When running the `lingui extract` command, the system encounters a syntax error due to the experimental syntax 'importAttributes' not being enabled. This error prevents the extraction of messages from source files that use the importAttributes syntax, such as:

```ts
import data from './data.json' assert { type: 'json' };
```

**To Reproduce**
1. Start a new Lingui project (https://lingui.dev/tutorials/setup-react)
2. Make use of 'importAttributes':
```shell
echo "import data from './data.json' assert { type: 'json' };" > src/bugged.js
```
3. Run the command `./node_modules/.bin/lingui extract --verbose`
4. Observe the error message related to the experimental syntax 'importAttributes'

```haskell
Extracting messages from source files…
⠋ Cannot process file /private/tmp/lingui-bug/src/bugged.js /private/tmp/lingui-bug/src/bugged.js: Support for the experimental syntax 'importAttributes' isn't currently enabled (1:32):

> 1 | import data from './data.json' assert { type: 'json' };
    |                                ^
  2 |

Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing.
SyntaxError: /private/tmp/lingui-bug/src/bugged.js: Support for the experimental syntax 'importAttributes' isn't currently enabled (1:32):

> 1 | import data from './data.json' assert { type: 'json' };
    |                                ^
  2 |

Add @babel/plugin-syntax-import-attributes (https://github.com/babel/babel/tree/main/packages/babel-plugin-syntax-import-attributes) to the 'plugins' section of your Babel config to enable parsing.
    at instantiate (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:63:32)
    at constructor (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:358:12)
    at JSXParserMixin.raise (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:3255:19)
    at JSXParserMixin.expectOnePlugin (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:3301:18)
    at JSXParserMixin.maybeParseImportAttributes (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14243:14)
    at JSXParserMixin.parseImportSourceAndAttributes (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14131:10)
    at JSXParserMixin.parseImportSpecifiersAndAfter (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14125:17)
    at JSXParserMixin.parseImport (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14116:17)
    at JSXParserMixin.parseStatementContent (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:12706:27)
    at JSXParserMixin.parseStatementLike (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:12584:17)
    at JSXParserMixin.parseModuleItem (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:12561:17)
    at JSXParserMixin.parseBlockOrModuleBlockBody (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:13185:36)
    at JSXParserMixin.parseBlockBody (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:13178:10)
    at JSXParserMixin.parseProgram (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:12460:10)
    at JSXParserMixin.parseTopLevel (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:12450:25)
    at JSXParserMixin.parse (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14347:10)
    at parse (/private/tmp/lingui-bug/node_modules/@babel/parser/lib/index.js:14388:38)
    at parser (/private/tmp/lingui-bug/node_modules/@babel/core/lib/parser/index.js:41:34)
    at parser.next (<anonymous>)
    at normalizeFile (/private/tmp/lingui-bug/node_modules/@babel/core/lib/transformation/normalize-file.js:64:38)
    at normalizeFile.next (<anonymous>)
    at run (/private/tmp/lingui-bug/node_modules/@babel/core/lib/transformation/index.js:21:50)
    at run.next (<anonymous>)
    at transform (/private/tmp/lingui-bug/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/private/tmp/lingui-bug/node_modules/gensync/index.js:261:32)
    at /private/tmp/lingui-bug/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/private/tmp/lingui-bug/node_modules/gensync/index.js:223:11)
    at /private/tmp/lingui-bug/node_modules/gensync/index.js:189:28
    at /private/tmp/lingui-bug/node_modules/@babel/core/lib/gensync-utils/async.js:68:7
    at /private/tmp/lingui-bug/node_modules/gensync/index.js:113:33
    at step (/private/tmp/lingui-bug/node_modules/gensync/index.js:287:14)
    at /private/tmp/lingui-bug/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/private/tmp/lingui-bug/node_modules/gensync/index.js:223:11)
✖
Catalog statistics for src/locales/{locale}/messages:
┌──────────┬─────────────┬─────────┐
│ Language │ Total count │ Missing │
└──────────┴─────────────┴─────────┘

(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
```

**Expected behavior**
The command should successfully extracted messages from source files without encountering a syntax error.

- jsLingui version ``lingui --version``: 4.2.1
- Babel version ``npm list @babel/core``: 7.22.5
- Your Babel config (e.g. `.babelrc`):
```json
{
  "plugins": [
    "macros"
  ]
}
```

**Comment by zvictor** [comment]
I tried adding `@babel/plugin-syntax-import-attributes` to the plugins list, but it didn't work either

**Comment by thekip** [comment]
Extractor doesn't support this syntax. You can override the default extractor and create your own with a set of plugins and syntax proposals you need. 

https://lingui.dev/guides/custom-extractor

I might consider adding the list of plugins as the extra params for default extractor to make this a little bit easier.
