### ISSUE TITLE
vite plugin with sourceLocale: Failed to resolve import "src/locales/en.po" from "src/locales/fr.po".

### ISSUE THREAD

**Issue by mdadoua** [lingui/js-lingui#1724]
Hello,

**Describe the bug**
I'm trying to use the vite plugin to compile the `.po` files on the fly but I can't get it to work when I use the `sourceLocale` configuration (it's very useful because `lingui extract` can automatically fill in the translations for the default locale in the `po` file when we use this configuration)

When the Lingui config file contains the `sourceLocale: 'fr'` property and I try to dynamically import the `en.po` file, I get the following error: 
```
[plugin:vite:import-analysis] Failed to resolve import "src/locales/fr.po" from "src/locales/en.po". Does the file exist?
```
**To Reproduce**
I reproduced the issue with the Vite+React+Typescript template.
```tsx
// vite.config.ts
import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";
import { lingui } from "@lingui/vite-plugin";

export default defineConfig({
  plugins: [
    react({
      babel: {
        plugins: ["macros"]
      }
    }),
    lingui()
  ]
});
```
```tsx
// lingui.config.ts
import type { LinguiConfig } from '@lingui/conf';

const linguiConfig: LinguiConfig = {
  locales: ['en', 'fr'],
  catalogs: [
    {
      path: 'src/locales/{locale}',
      include: ['src'],
    },
  ],
  sourceLocale: 'fr',
  compileNamespace: 'ts',
  format: 'po',
};

export default linguiConfig;
```
```tsx
// src/App.tsx
import {useEffect, useState} from 'react'
import './App.css'
import {Trans} from "@lingui/macro";
import {dynamicActivate} from "./i18n.ts";
import {I18nProvider} from "@lingui/react";
import {i18n} from "@lingui/core";

function App() {
  const [locale, setLocale] = useState("fr");
  useEffect(() => {
      dynamicActivate(locale);
  }, [locale]);

  return (
    <I18nProvider i18n={i18n}>
      <p>
          <button onClick={() => setLocale(locale === "fr" ? "en" : "fr")}>
              switch language
          </button>
          <Trans id="my.key">
              Cliquer ici
          </Trans>
      </p>
    </I18nProvider>
  )
}

export default App
```

```po
# src/locales/fr.po (generated with lingui extract)
msgid ""
msgstr ""
"POT-Creation-Date: 2023-07-04 14:58+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: @lingui/cli\n"
"Language: fr\n"

#. js-lingui-explicit-id
#: src/App.tsx:20
msgid "my.key"
msgstr "Cliquer ici"
```
```po
# src/locales/en.po (generated with lingui extract)
msgid ""
msgstr ""
"POT-Creation-Date: 2023-07-04 14:58+0200\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=utf-8\n"
"Content-Transfer-Encoding: 8bit\n"
"X-Generator: @lingui/cli\n"
"Language: en\n"

#. js-lingui-explicit-id
#: src/App.tsx:20
msgid "my.key"
msgstr "Click here"
```

**Expected behavior**
With the above setup and with `npm run dev`, I can initially see that the French `fr.po` file is dynamically imported without any issue. 
When I click on the "switch language" button, I expect the `en.po` file to be found by Vite and dynamically imported.
However, as soon as I click on the "switch language" button, Vite doesn't succeed in importing the `en.po` file.

I noticed that when I remove the `sourceLocale` configuration, then this works as expected. However, I lose the benefit of having the default translations automatically extracted by lingui.

**Additional context**
Vite error message when I click on the "switch language" button. Note that if I set the initial locale in the `useState` to be `en`, then this error occurs immediately.
```
 [vite] Internal server error: Failed to resolve import "src/locales/fr.po" from "src/locales/en.po". Does the file exist?
  Plugin: vite:import-analysis
  File: /Users/maxime/vite-lingui-react/src/locales/en.po:1:1
  1  |  /*eslint-disable*/export const messages=JSON.parse("{\"my.key\":\"Click here\"}");
     |  ^
      at formatError (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42645:46)
      at TransformContext.error (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42641:19)
      at normalizeUrl (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40508:33)
      at async Promise.all (index 0)
      at async TransformContext.transform (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:40807:22)
      at async Object.transform (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:42919:30)
      at async loadAndTransform (file:///Users/maxime/vite-lingui-react/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:53385:29) (x2)
```

- jsLingui version ``4.3.0``
- Babel version ``7.22.6``
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [x] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro

**Comment by thekip** [comment]
Try to add a `<rootDir>` into catalogs.path config:

```ts
import type { LinguiConfig } from '@lingui/conf';

const linguiConfig: LinguiConfig = {
  locales: ['en', 'fr'],
  catalogs: [
    {
      path: '<rootDir>/src/locales/{locale}',
      include: ['src'],
    },
  ],
  sourceLocale: 'fr',
  compileNamespace: 'ts',
  format: 'po',
};

export default linguiConfig;
```

**Comment by mdadoua** [comment]
Thank you, it works now!
