### ISSUE TITLE
Running `npx lingui extract` fails if spreading a MessageDescriptor on a Trans component

### ISSUE THREAD

**Issue by goibon** [lingui/js-lingui#1726]
**Describe the bug**
I have a use case where I would like to defer translation of strings but create the `MessageDescriptor` object in a TS (not TSX) context and then later pass it to the `Trans` component from `@lingui/react`. For conciseness I attempted to just spread the `message` object on the `Trans` component as the properties match with the props but this seems to break the extractor. However it does work if I map them out manually.
Perhaps this just comes down to misuse of the library but I could not seem to find anything about this in the docs or existing issues / discussions.

**To Reproduce**

The error occurs when I run `npx lingui extract`. In the following code snippet, the `extract` command fails if the `<Trans {...message} />` tag is present but it works if only the more verbose one is used.

```tsx
import React from "react";
import ReactDOM from "react-dom/client";
import { msg } from "@lingui/macro";
import { Trans } from "@lingui/react";

const message = msg`Hello world!`;

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    {/* This doesn't work */}
    <Trans {...message} />
    
    {/* This works */}
    <Trans
      id={message.id}
      message={message.message}
      values={message.values}
      comment={message.comment}
    />
  </React.StrictMode>
);
```

**Expected behavior**
I expected the extractor to extract the message from the `msg` macro line and update my translation catalogs.

**Additional context**

The output I get in the terminal when the extraction fails:
```
➜  /workspace git:(main) ✗ npx lingui extract
⠙ Cannot process file /workspace/src/main.tsx /workspace/src/main.tsx: Cannot read properties of undefined (reading 'name')
TypeError: /workspace/src/main.tsx: Cannot read properties of undefined (reading 'name')
    at /workspace/node_modules/@lingui/babel-plugin-extract-messages/dist/index.cjs:126:33
    at Array.reduce (<anonymous>)
    at PluginPass.JSXElement (/workspace/node_modules/@lingui/babel-plugin-extract-messages/dist/index.cjs:125:29)
    at newFn (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/visitors.js:153:14)
    at NodePath._call (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at NodePath.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/traverse-node.js:18:17)
    at traverse (/workspace/node_modules/@lingui/cli/node_modules/@babel/traverse/lib/index.js:49:34)
    at transformFile (/workspace/node_modules/@lingui/cli/node_modules/@babel/core/lib/transformation/index.js:81:29)
    at transformFile.next (<anonymous>)
    at run (/workspace/node_modules/@lingui/cli/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/workspace/node_modules/@lingui/cli/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/workspace/node_modules/gensync/index.js:261:32)
    at /workspace/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/workspace/node_modules/gensync/index.js:223:11)
    at /workspace/node_modules/gensync/index.js:189:28
    at /workspace/node_modules/@lingui/cli/node_modules/@babel/core/lib/gensync-utils/async.js:68:7
    at /workspace/node_modules/gensync/index.js:113:33
    at step (/workspace/node_modules/gensync/index.js:287:14)
    at /workspace/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/workspace/node_modules/gensync/index.js:223:11)
✖ 
Catalog statistics for src/locales/{locale}: 
┌──────────┬─────────────┬─────────┐
│ Language │ Total count │ Missing │
└──────────┴─────────────┴─────────┘

(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
```

- jsLingui version ``lingui --version``: 4.2.1
- Babel version ``npm list @babel/core``: 
  ```
  +-- @lingui/cli@4.2.1
  | `-- @babel/core@7.22.5
  |   `-- @babel/helper-compilation-targets@7.22.5
  |     `-- @babel/core@7.22.5 deduped
  `-- @vitejs/plugin-react@3.1.0
    +-- @babel/core@7.22.5 deduped
    +-- @babel/plugin-transform-react-jsx-self@7.18.6
    | `-- @babel/core@7.22.5 deduped
    `-- @babel/plugin-transform-react-jsx-source@7.19.6
      `-- @babel/core@7.22.5 deduped
  ```
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [X] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
  I use Vite with React and TypeScript

  ```TS
  // vite.config.ts
  import { defineConfig } from 'vite'
  import react from '@vitejs/plugin-react'
  import { lingui } from '@lingui/vite-plugin'
  import path from 'path'
  
  // https://vitejs.dev/config/
  export default defineConfig({
    plugins: [react({
      babel: {
        plugins: ['macros']
      }
    }),
    lingui()
    ],
    server: {
      host: true,
      port: 8000
    },
    resolve: {
      alias: {
        core: path.resolve(__dirname, './src/core'),
        shared: path.resolve(__dirname, './src/shared'),
        unshared: path.resolve(__dirname, './src/unshared')
      }
    },
    build: {
      sourcemap: true
    }
  })
  ```

**Comment by thekip** [comment]
Yes, spreading is not supported syntax by extractor. You should not do that. More over you don't need to spread whole message descriptor, you only need an id from it (and props of `Trans` component are not compatible with MessageDescriptor type)

```tsx
const message = msg`Hello world!`;

<Trans id={message.id} />
```

I believe this example is showcased in the docs.

**Comment by goibon** [comment]
> Yes, spreading is not supported syntax by extractor. You should not do that. More over you don't need to spread whole message descriptor, you only need an id from it (and props of `Trans` component are not compatible with MessageDescriptor type)

Thank you for the incredibly quick reply and thanks for the clarification that I only need to use the `id` property 🙂 

> I believe this example is showcased in the docs.

Looking at [the docs for the `Trans` component](https://lingui.dev/ref/react#trans) it seems it doesn't showcase any usecases where you just pass an id from a `MessageDescriptor` although I do realize that the props table only displays `id`.
[The docs for the `msg` macro](https://lingui.dev/ref/macro#definemessage) seem to only suggest that you pass the `MessageDescriptor` object to `i18n._`, but from your response I gather that it is also valid to pass the id property of it to a `Trans` component.
I guess this could be clarified a bit in some examples in there.

**Comment by thekip** [comment]
i believe it's described here: 

https://lingui.dev/tutorials/react-patterns#lazy-translations

We are welcome to make docs better.
