### ISSUE TITLE
Broken build on CI

### ISSUE THREAD

**Issue by andrii-bodnar** [lingui/js-lingui#1810]
For some unknown reason, the CI build step recently started failing ([latest pipeline](https://github.com/lingui/js-lingui/actions/runs/7016882300/job/19089749613)).

```console
...
[@lingui/format-json]: [info] Automatically detected entries: src/json [esm] [cjs] [dts]
[@lingui/format-json]: [info] Building format-json
[@lingui/format-json]: [info] Cleaning dist directory: `./dist`
[@lingui/format-json]: error TS6053: File '/home/runner/work/js-lingui/js-lingui/packages/format-po/dist/po.d.ts' not found.
[@lingui/format-json]:   The file is in the program because:
[@lingui/format-json]:     Root file specified for compilation
[@lingui/format-json]: 
[@lingui/format-json]: [error] Error building /home/runner/work/js-lingui/js-lingui/packages/format-json: RollupError: Failed to compile. Check the logs above.
[@lingui/format-json]: [error] Failed to compile. Check the logs above.
[@lingui/format-json]:   at error (/home/runner/work/js-lingui/js-lingui/node_modules/rollup/dist/es/shared/node-entry.js:2287:30)
[@lingui/format-json]:   at Object.error (/home/runner/work/js-lingui/js-lingui/node_modules/rollup/dist/es/shared/node-entry.js:25268:20)
[@lingui/format-json]:   at Object.error (/home/runner/work/js-lingui/js-lingui/node_modules/rollup/dist/es/shared/node-entry.js:24390:42)
[@lingui/format-json]:   at generateDtsFromTs (/home/runner/work/js-lingui/js-lingui/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1825:30)
[@lingui/format-json]:   at Object.transform (/home/runner/work/js-lingui/js-lingui/node_modules/rollup-plugin-dts/dist/rollup-plugin-dts.mjs:1834:38)
[@lingui/format-json]:   at /home/runner/work/js-lingui/js-lingui/node_modules/rollup/dist/es/shared/node-entry.js:25461:40
[@lingui/format-json]:   at process.processTicksAndRejections (node:internal/process/task_queues:95:5) 
[@lingui/format-json]: 
[@lingui/format-json]: [error] Failed to compile. Check the logs above.
[@lingui/format-json]: Process exited (exit code 1), completed in 5s 6ms
...
```

I have not been able to reproduce this locally. Any ideas why this might be happening?

**Comment by Kepro** [comment]
locally what is sequence? cuz on pipeline you can see that `format-json` is trying to read from `format-po`, but `format-po` is built later

**Comment by andrii-bodnar** [comment]
@Kepro you're right, the order is correct locally. It seems to have been fixed by @vonovak in #1781

**Comment by vonovak** [comment]
Yeah, what I did is a workaround I think - I removed the parallel flag, but it would be nice if there was a "real fix". Unfortunately it's not clear to me what that would be 🤷‍♂️😄

**Comment by thekip** [comment]
Well, the main question, why format-json is depending on format-po. I'm investigating
