### ISSUE TITLE
`Nextjs` `swc` plugin example not working

### ISSUE THREAD

**Issue by omrimor** [lingui/js-lingui#1846]
**Describe the bug**
We're trying to follow the example [`nextjs-swc`](https://github.com/lingui/js-lingui/tree/main/examples/nextjs-swc) provided in your `examples` folder and use `Lingui` with `Nextjs` using the `swc` plugin

**To Reproduce**
- Pulled the `[nextjs-swc](https://github.com/lingui/js-lingui/tree/main/examples/nextjs-swc)` folder
- Ran `npm i`
- Ran `npm run lingui:extract`
- Ran `npm run dev`

**Expected behavior**
The app should load with the translations working

**Actual**
The app can't load and throws with a big stacktrace (added below)

**Additional context**
```bash
$ next dev
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
warn  - You have enabled experimental feature (swcPlugins) in next.config.js.
warn  - Experimental features are not covered by semver, and may cause unexpected or broken application behavior. Use at your own risk.

thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable
    2: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/client/router.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/client/next-dev.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/pages/_error.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable
    2: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/src/utils.ts")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: LayoutError', /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rkyv-0.7.42/src/impls/core/mod.rs:266:67
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/pages/_error.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable
    2: unreachable', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/src/utils.ts")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
thread '<unnamed>' panicked at 'failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/pages/_document.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: out of bounds memory access
    2: heap_get_oob', /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/swc-0.260.23/src/plugin.rs:219:14
error - ./node_modules/next/dist/client/dev/amp-dev.js
Error: failed to process failed to invoke plugin: failed to invoke plugin on 'Some("/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/next/dist/client/dev/amp-dev.js")'

Caused by:
    0: failed to invoke `/Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm` as js transform plugin at /Users/omrimor1/Documents/code/lingui-nextjs-swc/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
    1: RuntimeError: unreachable
    2: unreachable
```

- jsLingui version `^4.7.0`,
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- `NextJs` config is the one in the example folder

**Comment by thekip** [comment]
there is too wide range provided for swc plugin it stated as `"@lingui/swc-plugin": "^4.0.0",`, but SWC plugins doesn't have semver compatibility (due to swc itself) so you need to [choose proper version for used swc_core](https://github.com/lingui/swc-plugin?tab=readme-ov-file#compatibility)

**Comment by omrimor** [comment]
It says `next@v14.1.0` should be compatible with `swc-plugin@4.0.5` which I tried but still see the same error

**Comment by thekip** [comment]
They added a note yesterday, just after we've made a release 😬

Fix: 
https://github.com/lingui/swc-plugin/pull/81

And note: 
https://github.com/swc-project/swc/issues/8613
