### ISSUE TITLE
ERROR in ./node_modules/@lingui/macro/dist/index.mjs 347:24 Module parse failed

### ISSUE THREAD

**Issue by stoefln** [lingui/js-lingui#1860]
**Describe the bug**
When I try to run my electron project (using webpack), and sources are getting transpiled, I am getting this error:

```
ERROR in ./node_modules/@lingui/macro/dist/index.mjs 347:24
Module parse failed: Unexpected token (347:24)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     return this.types.callExpression(
|       this.types.memberExpression(
>         linguiInstance ?? this.types.identifier(this.i18nImportName),
|         this.types.identifier("_")
|       ),
 @ ./app/main.js 21:0-38 86:83-88
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=3000&sockProtocol=http ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=3000&sockProtocol=http @babel/polyfill ./app/main.js
```

**To Reproduce**

Not exactly sure. I mentioned that this is an electron project and I can't share all of it.

```jsx
import { Trans } from "@lingui/macro"
```

Here is the webpack config:

```
const config = {
  devtool: 'eval-cheap-module-source-map',
  entry: {
    main: ['@babel/polyfill', './app/main.js'],
    loading: ['@babel/polyfill', './app/loading.js']
  },
  mode: 'development',
  output: {
    filename: '[name]-bundle.js',
    path: path.resolve(__dirname, 'dist'),
    publicPath: '/'
  },

  module: {
    rules: [
      {
        test: /\.worker\.(c|m)?js$/i,
        loader: 'worker-loader',
        options: {
          worker: 'SharedWorker'
        }
      },
      {
        test: /\.node$/,
        use: 'node-loader'
      },
      {
        test: /\.(ts|tsx)$/,
        exclude: /node_modules/,
        use: 'ts-loader'
      },
      {
        test: [/\.bmp$/, /\.gif$/, /\.jpe?g$/, /\.png$/],
        loader: require.resolve('url-loader'),
        options: {
          limit: imageInlineSizeLimit,
          name: 'static/media/[name].[hash:8].[ext]'
        }
      },
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_compontents)\/(?!(aws-sdk|@aws-sdk|@smithy)\/).*/,
        use: {
          loader: 'babel-loader',
          options: {
            presets: ['@babel/preset-env']
          }
        }
        // exclude: /(node_modules|bower_compontents)\/(?!(aws-sdk|@aws-sdk)\/).*/,
        // use: ["babel-loader"],
      },
      {
        test: /\.mjs$/,
        include: /node_modules/,
        type: 'javascript/auto'
      },
      {
        test: /\.css$/,
        use: ['style-loader', 'css-loader']
      },
      {
        test: /\.(asset)$/i,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[name]'
            }
          }
        ]
      },
      {
        test: /\.jar$/,
        use: [
          {
            loader: 'file-loader',
            options: {
              name: '[path][name].[ext]'
            }
          }
        ]
      }
    ]
  },

  plugins,
  externals: {
    'monaco-editor': 'monaco-editor'
  },
  resolve: {
    extensions: ['.ts', '.tsx', '.js', '.jsx']
  },

  devServer: {
    host: 'localhost',
    port: process.env.PORT || 3000,
    historyApiFallback: true,
    hot: true
  },
  target: 'electron-renderer',

  watchOptions: {
    poll: 1000,
    ignored: ['node_modules/**'],
    aggregateTimeout: 600
  }
}
module.exports = config
```

**Expected behavior**
No error, file transpiles

**Additional context**

- jsLingui version ``"@lingui/cli": "^4.7.1",
    "@lingui/macro": "^4.7.1"``
- Babel version ``7.23.9``
- Macro support:
 - [ ] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro <- not sure?
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite): 

```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "env": {
    "production": {
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining"
      ]
    },
    "development": {
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining",
        "react-refresh/babel",
        [
          "i18next-extract",
          {
            "locales": ["en", "de"],
            "defaultNS": "common",
            "keySeparator": null,
            "nsSeparator": "::",
            "defaultValue": null
          }
        ]
      ]
    },
    "test": {
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining",
        "i18next-extract",
        [
          "@babel/plugin-transform-runtime",
          {
            "regenerator": true
          }
        ]
      ]
    }
  }
}

```

**Comment by stoefln** [comment]
@thekip thanks for your quick help!
I installed the plugin and added it to the .babelrc, now I am getting this error

```
ERROR in ./app/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: /Users/steph/Workspace/myapp-studio/app/main.js: Cannot find module '@lingui/macro' from '/Users/steph/Workspace/myapp-studio/app'
    at Function.resolveSync [as sync] (/Users/steph/Workspace/myapp-studio/node_modules/resolve/lib/sync.js:111:15)
    at nodeResolvePath (/Users/steph/Workspace/myapp-studio/node_modules/babel-plugin-macros/dist/index.js:62:18)
    at applyMacros (/Users/steph/Workspace/myapp-studio/node_modules/babel-plugin-macros/dist/index.js:203:23)
    at ImportDeclaration (/Users/steph/Workspace/myapp-studio/node_modules/babel-plugin-macros/dist/index.js:110:28)
    at NodePath._call (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/index.js:52:34)
    at NodePath.traverse (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/index.js:101:24)
    at PluginPass.Program (/Users/steph/Workspace/myapp-studio/node_modules/babel-plugin-macros/dist/index.js:91:18)
    at newFn (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/steph/Workspace/myapp-studio/node_modules/@babel/traverse/lib/index.js:52:34)
    at transformFile (/Users/steph/Workspace/myapp-studio/node_modules/@babel/core/lib/transformation/index.js:82:31)
    at transformFile.next (<anonymous>)
    at run (/Users/steph/Workspace/myapp-studio/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/steph/Workspace/myapp-studio/node_modules/@babel/core/lib/transform.js:22:33)
    at transform.next (<anonymous>)
    at step (/Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:261:32)
    at /Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:223:11)
    at /Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:189:28
    at /Users/steph/Workspace/myapp-studio/node_modules/@babel/core/lib/gensync-utils/async.js:67:7
    at /Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:113:33
    at step (/Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:287:14)
    at /Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/steph/Workspace/myapp-studio/node_modules/gensync/index.js:223:11)
 @ multi ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=3000&sockProtocol=http ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ReactRefreshEntry.js ./node_modules/@pmmmwh/react-refresh-webpack-plugin/client/ErrorOverlayEntry.js?sockHost=localhost&sockPort=3000&sockProtocol=http @babel/polyfill ./app/main.js main[5]
```

My .babelrc now:

```
{
  "presets": ["@babel/preset-env", "@babel/preset-react"],
  "env": {
    "production": {
      "plugins": [
        "macros",
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining"
      ]
    },
    "development": {
      "plugins": [
        "macros",
        [ "@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining",
        "react-refresh/babel",
        [
          "i18next-extract",
          {
            "locales": ["en", "de"],
            "defaultNS": "common",
            "keySeparator": null,
            "nsSeparator": "::",
            "defaultValue": null
          }
        ]
      ]
    },
    "test": {
      "plugins": [
        ["@babel/plugin-proposal-decorators", { "legacy": true }],
        "@babel/plugin-proposal-class-properties",
        "@babel/plugin-syntax-optional-chaining",
        "i18next-extract",
        [
          "@babel/plugin-transform-runtime",
          {
            "regenerator": true
          }
        ]
      ]
    }
  }
}

```

**Comment by thekip** [comment]
Have you installed @lingui/macro?

**Comment by stoefln** [comment]
Yes, sure. v4.7.1

**Comment by thekip** [comment]
Unfortunately, i couldn't help with the issue without a reproduction repo.

**Comment by stoefln** [comment]
Could you maybe still reopen the issue? Someone else might be able to help...

**Comment by thekip** [comment]
@stoefln check your configuration. It's 100% problem in your setup, not in the Lingui.  Go through one of examples and compare to your setup. No one will to debug your code instead of you.
