### ISSUE TITLE
Internal Server Error running nextjs-swc example with nodeLinker: pnp in .yarnrc.yml

### ISSUE THREAD

**Issue by neemski** [lingui/js-lingui#2005]
**Describe the bug**
Hey lingui team 👋 . I'm running into errors running the app with the latest [nextjs-swc example](https://github.com/lingui/js-lingui/tree/6d0030146cc73f457e4cdcd1837f3d8f060d16fc/examples/nextjs-swc) when using Yarn 4.x with `nodeLinker: pnp`.

**To Reproduce**
1. Clone this repo, `cd examples/nextjs-swc/`
2. Run `yarn set version stable`
3. Edit `.yarnrc.yml`, add `nodeLinker: pnp`
4. Run `yarn install`
5. (At this point I had to `yarn add @types/node --dev` to get things running)
6. `yarn dev`

(Included a diff here too: [diff.patch](https://github.com/user-attachments/files/16647285/diff.patch))

**Expected behavior**
- Sample app should run

**Actual behavior**
- I get the following console error:
```
$  ~/dev/lingui/examples/nextjs-swc   main ±✚  yarn dev           
  ▲ Next.js 14.2.3
  - Local:        http://localhost:3000
  - Experiments (use with caution):
    · swcPlugins

 ✓ Starting...
 ✓ Ready in 2.5s
 ⨯ ./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/esm/client/components/app-router-headers.js
Error: index not found

Import trace for requested module:
./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/esm/client/components/app-router-headers.js
 ○ Compiling /src/middleware ...
 ⨯ ./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/client/next-dev.js
Error: index not found
 ⨯ ./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/client/next-dev.js
Error: index not found
 ⨯ ./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/pages/_document.js
Error: index not found
 ⨯ ./.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/client/next-dev.js
Error: index not found
Error: ENOENT: no such file or directory, open '/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.next/fallback-build-manifest.json'
    at Object.readFileSync (node:fs:453:20)
    at NodeFS.readFileSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:8824:24)
    at makeCallSync.subPath.subPath (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:9517:26)
    at ZipOpenFS.makeCallSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:9639:14)
    at ZipOpenFS.readFileSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:9516:17)
    at VirtualFS.readFileSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:8430:24)
    at PosixFS.readFileSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:8430:24)
    at NodePathFS.readFileSync (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.pnp.cjs:8430:24)
    at loadManifest (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/load-manifest.js:35:54)
    at loadManifestWithRetries (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/load-components.js:40:51)
    at runNextTicks (node:internal/process/task_queues:60:5)
    at process.processTimers (node:internal/timers:511:9)
    at async loadDefaultErrorComponentsImpl (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/load-default-error-components.js:30:24)
    at async DevServer.getFallbackErrorComponents (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/dev/next-dev-server.js:594:16)
    at async DevServer.renderErrorToResponseImpl (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/base-server.js:2203:40)
    at async pipe.req.req (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/base-server.js:2056:30)
    at async DevServer.pipeImpl (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/base-server.js:920:25)
    at async NextNodeServer.handleCatchallMiddlewareRequest (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/next-server.js:357:21)
    at async DevServer.handleRequestImpl (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/base-server.js:822:28)
    at async /Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/dev/next-dev-server.js:339:20
    at async Span.traceAsyncFn (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/trace/trace.js:154:20)
    at async DevServer.handleRequest (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/dev/next-dev-server.js:336:24)
    at async handleRoute (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:305:33)
    at async resolveRoutes (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/lib/router-utils/resolve-routes.js:525:28)
    at async handleRequest (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/lib/router-server.js:211:96)
    at async requestHandlerImpl (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/lib/router-server.js:377:13)
    at async Server.requestListener (/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.yarn/__virtual__/next-virtual-cd9fadbd32/0/cache/next-npm-14.2.3-7770cdfada-666c977020.zip/node_modules/next/dist/server/lib/start-server.js:141:13) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/nima-mbp/dev/lingui/examples/nextjs-swc/.next/fallback-build-manifest.json'
}
```

**Additional context**
- This doesn't happen with `nodeLinker: node-modules` - everything works fine there.
- I also tried `examples/nextjs-babel` with `nodeLinker: pnp`, and that worked.
- With the yarn version that ships with this project (`yarn@3.4.1`), I couldn't get past `yarn install` with `nodeLinker: pnp`
- Also reproduced on `yarn@4.0.2`

**Settings**
- Node: `v20.10.0`
- jsLingui version `4.11.0`
- Macro support:
 - [x] I'm using SWC with `@lingui/swc-plugin`
 - [ ] I'm using Babel with `babel-macro-plugin`
 - [ ] I'm not using macro
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, NextJs, Vite)
  - Next.js

**Comment by thekip** [comment]
Does the clean nextjs project with SWC works with`nodeLinker: pnp`? i'm afraid that might be an upstream issue with swc or next not the lingui

**Comment by neemski** [comment]
Ahh @thekip you're right - looks like SWC doesn't support yarn pnp for plugins as of yet https://github.com/swc-project/swc/issues/3247

I verified this with create next app, `nodeLinker: pnp`, and adding a random (non-lingui) SWC plugin to my next config, and I get the same error. Thanks for the help! 🙏

**Comment by thekip** [comment]
You probably can workaround it by specifying full path to the wasm assembly, or if it's not possible (because it's behind yarn zip archive) simply copy and paste the wasm binary to your project.

**Comment by neemski** [comment]
@thekip followed your suggested workaround and wrote a script that copies the wasm binary from the yarn pnp cache (by just referencing `@lingui/swc-plugin`), copies it to `/bin/lingui_swc_plugin.wasm` in the project, and returns that path. Not sure if this will help anyone else but figured I'd share it:

```js
// scripts/copy-lingui-swc-plugin.js';
import path from 'node:path';
import yarnfslib from '@yarnpkg/fslib';
import yarnlibzip from '@yarnpkg/libzip';
import pnpapi from 'pnpapi';

const { PosixFS } = yarnfslib;
const { getLibzipSync, ZipOpenFS } = yarnlibzip;
const { resolveRequest, resolveVirtual } = pnpapi;

const libzip = getLibzipSync();
// This will transparently open zip archives
const zipOpenFs = new ZipOpenFS({ libzip });
// This will convert all paths into a Posix variant, required for cross-platform compatibility
const crossFs = new PosixFS(zipOpenFs);

// This will point to the swc wasm binary in .yarn/cache, without __virtual__ in the path.
// e.g. .yarn/cache/@lingui-swc-plugin-npm-4.0.8-fdd72fbb14-b93d924f49.zip/node_modules/@lingui/swc-plugin/target/wasm32-wasi/release/lingui_macro_plugin.wasm
const swcPluginPathFromYarnCache = resolveVirtual(
  resolveRequest('@lingui/swc-plugin', process.cwd())
);

if (!crossFs.existsSync('./bin')) {
  crossFs.mkdirSync('./bin');
}

const copiedSwcPluginPath = path.resolve('./bin/lingui_swc_plugin.wasm');
crossFs.copyFileSync(swcPluginPathFromYarnCache, copiedSwcPluginPath);

export default copiedSwcPluginPath;
```
```js
// next.config.js
import path from 'node:path';
const linguiSwcPluginPath = path.resolve('./bin/lingui_swc_plugin.wasm');

/**
 * @type {import('next').NextConfig}
 */
const nextConfig = {
  experimental: {
    swcPlugins: [[linguiSwcPluginPath, {}]],
  },
```
The only caveat is the script would have to be run before running `next dev`/`next build` etc, but not a big deal. I tried just referencing `swcPluginPathFromYarnCache` in `nextConfig.experimental.swcPlugins` - but the .zip causes issues like you predicted!

**Comment by thekip** [comment]
You can add the script on the `postinstall`l or `prepare` in package.json so it would be called automatically with `npm/yarn install`

**Comment by trzmaxim** [comment]
`yarn unplug @lingui/swc-plugin` helped me solve the problem
