### ISSUE TITLE
babel/types warning when using lingui/cli

### ISSUE THREAD

**Issue by nmoinvaz** [lingui/js-lingui#2105]
**Describe the bug**
Get a warning about missing `@babel/types` when running `@lingui/cli`:
```
PS D:\x> yarn lingui extract src
D:\x\.pnp.cjs:21930
      Error.captureStackTrace(firstError);
            ^

Error: @lingui/babel-plugin-extract-messages tried to access @babel/types, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

Required package: @babel/types (via "@babel\types")
Required by: @lingui/babel-plugin-extract-messages@npm:5.0.0 (via D:\x\.yarn\cache\@lingui-babel-plugin-extract-messages-npm-5.0.0-22325ac964-7372573713.zip\node_modules\@lingui\babel-plugin-extract-messages\dist\)

Require stack:
- D:\x\.yarn\cache\@lingui-babel-plugin-extract-messages-npm-5.0.0-22325ac964-7372573713.zip\node_modules\@lingui\babel-plugin-extract-messages\dist\index.cjs
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\extractors\babel.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\extractors\index.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\catalog\extractFromFiles.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\catalog.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\catalog\getCatalogs.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\api\index.js
- D:\x\.yarn\cache\@lingui-cli-npm-5.0.0-ba7d96b184-b1f16ff0d0.zip\node_modules\@lingui\cli\dist\lingui-extract.js
    at require$$0.Module._resolveFilename (D:\x\.pnp.cjs:21930:13)
    at Module._load (node:internal/modules/cjs/loader:922:27)
    at require$$0.Module._load (D:\x\.pnp.cjs:21819:31)
    at Module.require (node:internal/modules/cjs/loader:1143:19)
    at require (node:internal/modules/cjs/helpers:119:18)
    at Object.<anonymous> (D:\x\.yarn\cache\@lingui-babel-plugin-extract-messages-npm-5.0.0-22325ac964-7372573713.zip\node_modules\@lingui\babel-plugin-extract-messages\dist\index.cjs:3:15)
    at Module._compile (node:internal/modules/cjs/loader:1256:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)
    at require$$0.Module._extensions..js (D:\x\.pnp.cjs:21974:33)
    at Module.load (node:internal/modules/cjs/loader:1119:32)

Node.js v18.18.0
```

**To Reproduce**

```
yarn add --dev @lingui/cli
yarn lingui extract src
```

**Expected behavior**
No warning, no need to install additional dependencies.

**Additional context**

- Vite, React, Node 18

**Comment by timofei-iatsenko** [comment]
Important to add that this happened with yarn pnp only...

I'll fix it.
