### ISSUE TITLE
[extract] Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3"

### ISSUE THREAD

**Issue by alampros** [lingui/js-lingui#327]
**Describe the bug**
After upgrading to babel@7, `lingui extract` fails with this error.

```
/PROJECT_PATH/node_modules/@babel/helper-plugin-utils/lib/index.js:72
  throw Object.assign(err, {
  ^

Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.
    at throwVersionError (/PROJECT_PATH/node_modules/@babel/helper-plugin-utils/lib/index.js:65:11)
    at Object.assertVersion (/PROJECT_PATH/node_modules/@babel/helper-plugin-utils/lib/index.js:13:11)
    at api (/PROJECT_PATH/node_modules/@babel/plugin-syntax-dynamic-import/lib/index.js:19:7)
    at /PROJECT_PATH/node_modules/@babel/helper-plugin-utils/lib/index.js:19:12
    at Function.memoisePluginContainer (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
    at Function.normalisePlugin (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
    at /PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
    at Array.map (<anonymous>)
    at Function.normalisePlugins (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/PROJECT_PATH/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transformFileSync (/PROJECT_PATH/node_modules/babel-core/lib/api/node.js:152:10)
    at Object.extract (/PROJECT_PATH/node_modules/@lingui/cli/api/extractors/babel.js:52:38)
    at /PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:90:11
    at Array.some (<anonymous>)
    at /PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:84:56
    at Array.forEach (<anonymous>)
    at extract (/PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:72:12)
    at /PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:80:7
    at Array.forEach (<anonymous>)
    at extract (/PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:72:12)
    at /PROJECT_PATH/node_modules/@lingui/cli/api/extract.js:80:7
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

1. Upgrade to babel@7
2. Run `lingui extract`

**Expected behavior**
Tokens extracted (duh), or provide a little more help in identifying which package is causing the old babel version to be loaded maybe?

**Additional context**

- jsLingui version ``lingui --version``: 2.7.0
- Babel version ``npm list babel-core``: 6.26.3
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
```json
{
  "presets": [
    [
      "@babel/preset-env",
      {
        "targets": {
          "browsers": [
            ">1%",
            "not ie 10",
            "ie 11",
            "not op_mini all"
          ]
        }
      }
    ],
    "@babel/preset-react",
    "@lingui/babel-preset-react"
  ],
  "plugins": [
    "@babel/plugin-syntax-dynamic-import",
    "@babel/plugin-proposal-class-properties",
    "@babel/plugin-proposal-object-rest-spread",
    "react-hot-loader/babel"
  ],
  "env": {
    "test": {
      "plugins": [
        "dynamic-import-node"
      ]
    }
  }
}
```

**Comment by tricoder42** [comment]
Hey @alampros,
you indeed have babel-core@6:

```
at Function.memoisePluginContainer (/PROJECT_PATH/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
```

What's the full output or `yarn why babel-core` or `npm list babel-core`?

**Comment by alampros** [comment]
Thanks for the quick response, @tricoder42 !

It looks like `react-select` is the culprit:

```
> yarn why babel-core
yarn why v1.9.4
[1/4] 🤔  Why do we have the module "babel-core"...?
[2/4] 🚚  Initialising dependency graph...
[3/4] 🔍  Finding dependency...
[4/4] 🚡  Calculating file sizes...
=> Found "babel-register#babel-core@6.26.0"
info This module exists because "react-select#emotion#babel-plugin-emotion#babel-core#babel-register" depends on it.
info Disk size without dependencies: "176MB"
info Disk size with unique dependencies: "39.93GB"
info Disk size with transitive dependencies: "50.68GB"
info Number of shared dependencies: 44
```

Any ideas on how I can work around it?

**Comment by tricoder42** [comment]
It seems to be issue with babel-plugin-emotion. I don't understand why, but `8.0.12` uses Babel 7, but latest uses Babel 6.

But you don't use babel-plugin-emotion at all, at it's not direct dependency of emotion nor react-select. Could you please try remove `babel-plugin-emotion`? Do you have latest versions of all other packages?

**Comment by alampros** [comment]
babel-plugin-emotion is not a direct dep and all other deps are up-to-date.

```
> yarn remove babel-plugin-emotion
yarn remove v1.9.4
[1/2] 🗑  Removing module babel-plugin-emotion...
error This module isn't specified in a manifest.
info Visit https://yarnpkg.com/en/docs/cli/remove for documentation about this command.

> yarn outdated
yarn outdated v1.9.4
✨  Done in 1.43s.
```

**Comment by tricoder42** [comment]
Yeah, it's weird. `yarn why babel-core` shows this:

```
react-select#emotion#babel-plugin-emotion#babel-core#babel-register
```

It seems like babel-plugin-emotion is installed because emotion which is required by react-select, but unfortunately neither react-select nor emotion depend on babel-plugin-emotion.

I can't help you here. Looks like a weird dependency problem. Please share your solution when you find it! 👍 

Also, try to inspect yarn.lock for any dependencies above. If you find babel-plugin-emotion there, try to simply remove it and run `yarn install`

**Comment by FredyC** [comment]
Or you can just try `yarn install --no-lockfile` to ignore `yarn.lock` temporarily so it would install all dependencies according to package.json again.

**Comment by alampros** [comment]
In case anyone else has this issue, I figured this out finally – turns out I missed the `babel-core@7.0.0-bridge.0` requirement. It was added pretty quietly in c254d91438b12a4d87128ae3dbcb4c634557b1ad.

**Comment by tricoder42** [comment]
Quietly? The dependency is there since 2.3. In that commit the version was fixed from former `babel-core@7.0.0-0` to `babel-core@7.0.0-bridge.0`, a version fix introduced in `babel-bridge` package.

I understand this situation is annoying, but as far as I know this is the standard way to support both versions of Babel. [Babel-jest](https://jestjs.io/docs/en/getting-started#using-babel) has the same requirement. I wish there was easier way though. 

I'm glad you made it work! 👍

**Comment by alampros** [comment]
I apologize if that sounded catty – by "quietly", I only meant that the "getting started" routine had changed since I got started. I just needed to RTFM. 🤣 

The situation is far from annoying - doing all this i18n work without lingui would be annoying. Thank you for this amazing tool!

**Comment by tricoder42** [comment]
Thank you 👍 Point taken, the "getting started" routine really had changed a lot and it's not documented enough ((#331). I'm just in the middle of fixing it (#334). In next version CLI should show a warning about misconfigured Babel.
