### ISSUE TITLE
lingui-cli extract

### ISSUE THREAD

**Issue by LFDMR** [lingui/js-lingui#41]
Hi,
I have upgraded the package since last time, here is my config:
```
├─┬ babel-preset-lingui-react@1.0.1
│ ├── babel-plugin-lingui-transform-js@1.0.1
│ └── babel-plugin-lingui-transform-react@1.0.1
├─┬ lingui-cli@1.0.4
│ ├── babel-plugin-lingui-extract-messages@1.0.2
├─┬ lingui-conf@0.8.1
├─┬ lingui-i18n@1.0.1
│ └── lingui-formats@1.0.1
├── lingui-react@1.0.1
```

But I encounter a problem when I do `lingui extract`, `Unexpected token`.
The code is fine and works when I `yarn build` it or `yarn start` it 

```
yarn lingui v0.27.5
$ "/home/lfdmr/Dev/test/web_frontend/node_modules/.bin/lingui" "extract"

/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babel-core/lib/transformation/file/index.js:590
      throw err;
      ^

SyntaxError: /home/lfdmr/Dev/test/web_frontend/src/App1/components/App.js: Unexpected token (6:2)
  4 | 
  5 | const App = () => (
> 6 |   <h1><Trans>Welcome App 1!</Trans></h1>
    |   ^
  7 | )
  8 | 
  9 | export default App
    at Parser.pp$5.raise (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$3.parseExprAtom (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3474:19)
    at Parser.pp$3.parseExprOps (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3344:19)
    at Parser.pp$3.parseParenAndDistinguishExpression (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3828:26)
    at Parser.pp$3.parseExprAtom (/home/lfdmr/Dev/test/web_frontend/node_modules/lingui-cli/node_modules/babylon/lib/index.js:3709:19)
error Command failed with exit code 1.
```

Thanks

**Comment by tricoder42** [comment]
Do you use Create React App?

How does your babel config looks like?

**Comment by LFDMR** [comment]
The project I used is from
[https://github.com/davezuko/react-redux-starter-kit](url)

And I have modified the app.js to the bare minimum in order to test your amazing project.
in ~/routes/Home/components/HomeView.js
```
import React from 'react'
import { Trans } from 'lingui-react'

export const HomeView = () => (
  <div>
    <h1><Trans>Welcome App 1!</Trans></h1>
  </div>
)

export default HomeView
```

**Comment by tricoder42** [comment]
I see, thank you. This is another project with hard-codes babel config inside webpack.

Temporary workaround - add **.babelrc** to root of your app (copy of config from react-redux-starter-kit):

```json
{
  "plugins": [
    "babel-plugin-transform-class-properties",
    "babel-plugin-syntax-dynamic-import",
    [
      "babel-plugin-transform-runtime",
      {
        "helpers": true,
        "polyfill": false,
        "regenerator": true,
      },
    ],
    [
      "babel-plugin-transform-object-rest-spread",
      {
        "useBuiltIns": true
      },
    ],
  ],
  "presets": [
    "babel-preset-react",
    ["babel-preset-env", {
      "modules": false,
      "targets": {
        "ie9": true,
      },
      "uglify": true,
    }],
    "lingui-react"  // add lingui preset here
  ]
}
```

Once you have this, you can remove it from [webpack config](https://github.com/davezuko/react-redux-starter-kit/blob/master/build/webpack.config.js#L57).

Meanwhile I need to figure out how to solve this problem in more elegant way.  Problem is that configs hard-coded inside webpack (react-redux-starter-kit, create-react-app, neutrino, ...) can't be read or extended by external tools (lingui-cli).

Feel free to reopen if it doesn't solve your problem 👍

**Comment by tricoder42** [comment]
Added section about integrations to docs https://lingui.gitbooks.io/js/guides/integrations.html

**Comment by iamnimnul** [comment]
I had same error but caused by the different issue. `react-scripts` were missing in dependencies. https://github.com/lingui/js-lingui/issues/434

```diff
{
  // ...
  "dependencies": {
    "@lingui/react": "^2.7.2",
    "react": "^16.6.1",
    "react-dom": "^16.6.1",
    "react-router-dom": "^4.3.1",
+   "react-scripts": "^2.1.3",
    // ...
  }
  // ...
}
```
