### ISSUE TITLE
Extract chokes on "obj?.function" (optional-chaining + "function" attribute)

### ISSUE THREAD

**Issue by vitexikora** [lingui/js-lingui#429]
**Describe the bug**
Cannot parse source code containing a optional chaining followed by an attribute name "function".

**To Reproduce**

```
export default function App() {
   return news.author?.function // fails
  // news.author?.['function'] is OK
  // news.author.function is also OK
}
```
```
SyntaxError: src\containers\news\NewsDetail.js: Unexpected token (68:45)

  66 |       authorAvatarUrl={null}
  67 |       authorFullName={news.author?.fullName}
> 68 |       authorFunction={news.author?.function}
     |                                              ^
  69 |       categoryName={news.category?.name}
  70 |       categoryColorObject={news.category?.color}
  71 |       content={news.content}
    at _class.raise (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:4051:15)
    at _class.unexpected (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:5382:16)
    at _class.jsxParseIdentifier (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3527:14)
    at _class.jsxParseNamespacedName (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3537:23)
    at _class.jsxParseAttribute (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3620:24)
    at _class.jsxParseOpeningElementAfterName (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3641:30)
    at _class.jsxParseOpeningElementAt (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3634:19)
    at _class.jsxParseElementAt (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3666:33)
    at _class.jsxParseElement (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3735:19)
    at _class.parseExprAtom (node_modules\@babel\core\node_modules\@babel\parser\lib\index.js:3742:21)
```

**Expected behavior**
To work

**Additional context**
js-lingui 2.7.2
@babel/plugin-proposal-optional-chaining
(plugin included in extractBabelOptions)

**Comment by wtgtybhertgeghgtwtg** [comment]
`foo?.bar` is optional chaining, not nullish coalescing (which would be `foo ?? bar`).

**Comment by vitexikora** [comment]
Thats true, my bad.

**Comment by vitexikora** [comment]
package.json with lingui config: https://pastebin.com/arJkrSg1
(with config in .linguirc it was throwing errors ...)
.babelrc: https://pastebin.com/McUE57bn
webpack.config.js: https://pastebin.com/5uVhJdy3

**Comment by jbbr** [comment]
I have the same issue, since TypeScript 3.7 beta+ includes this feature, it's gaining popularity.
I would have expected this to work since lingui extract uses babel anyway.
Maybe this plugin for some reason doesn't work with babel-bridge compatibility package...

**Comment by moodysalem** [comment]
I'm running into this somehow

optional chaining is broken with vite, `@lingui/vite-plugin`, and `@lingui/swc-plugin`

**Comment by thekip** [comment]
@moodysalem  i'm pretty sure (95%) that you have versions misalignment. Please read [compatibility](https://github.com/lingui/swc-plugin#compatibility) section carefully and adjust your project accordingly.
