### ISSUE TITLE
Dynamic import is not supported

### ISSUE THREAD

**Issue by yaitskov** [lingui/js-lingui#432]
**Is your feature request related to a problem? Please describe.**
I am trying to build light application on top of preact. I want to split app into parts via dynamic loading.
My app must have i18n. Once I attached linguijs according the manual translation extracting fails:

```
 npm run extract-trans

> babel-ts-7@1.0.0 extract-trans /home/dan/demo/preact/babel-ts-7
> lingui extract

/home/dan/demo/preact/babel-ts-7/node_modules/@lingui/cli/api/compat.js:48
        throw e;
        ^

SyntaxError: /home/dan/demo/preact/babel-ts-7/src/app.tsx: Support for the experimental syntax 'dynamicImport' isn't currently enabled (18:34):

  16 |         this.Profile = () => __awaiter(this, void 0, void 0, function* () {
  17 |             console.log("profile page is requested");
> 18 |             const module = yield import('./components/Profile');
     |                                  ^
  19 |             return module.default;
  20 |         });
  21 |         this.Terms = () => __awaiter(this, void 0, void 0, function* () {

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.
    at _class.raise (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:4051:15)
    at _class.expectPlugin (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:5387:18)
    at _class.parseExprAtom (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:6371:14)
    at _class.parseExprAtom (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:3747:52)
    at _class.parseExprSubscripts (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:6104:21)
    at _class.parseMaybeUnary (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:6083:21)
    at _class.parseExprOps (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:5968:21)
    at _class.parseMaybeConditional (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:5940:21)
    at _class.parseMaybeAssign (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:5887:21)
    at _class.parseYield (/home/dan/demo/preact/babel-ts-7/node_modules/@babel/parser/lib/index.js:7328:28)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! babel-ts-7@1.0.0 extract-trans: `lingui extract`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the babel-ts-7@1.0.0 extract-trans script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/dan/.npm/_logs/2019-01-13T18_16_30_398Z-debug.log
10:16$
```

**Comment by yaitskov** [comment]
my bad. I missed section
```
  "extractBabelOptions": {
    "plugins": ["@babel/plugin-syntax-dynamic-import"]
  }

```
in .linguirc
