### ISSUE TITLE
Support React.Fragment shorthand <> tags.

### ISSUE THREAD

**Issue by chrischen** [lingui/js-lingui#459]
**Is your feature request related to a problem? Please describe.**
When running lingui extract, `<React.Fragment></React.Fragment>` works, but `<></>` shorthand does not work.

**Describe the solution you'd like**
It should work without having to use React.Fragment tags explicitly.

**Describe alternatives you've considered**
I have to convert all `<></>` to `<React.Fragment></React.Fragment>`.

**Additional context**
Stack trace for the failure.
```
 at Parser.pp$5.raise (./node_modules/babylon/lib/index.js:4454:13)
    at Parser.pp.unexpected (./node_modules/babylon/lib/index.js:1761:8)
    at Parser.pp$9.jsxParseIdentifier (./node_modules/babylon/lib/index.js:7029:10)
    at Parser.pp$9.jsxParseNamespacedName (./node_modules/babylon/lib/index.js:7040:19)
    at Parser.pp$9.jsxParseElementName (./node_modules/babylon/lib/index.js:7055:19)
    at Parser.pp$9.jsxParseOpeningElementAt (./node_modules/babylon/lib/index.js:7145:20)
    at Parser.pp$9.jsxParseElementAt (./node_modules/babylon/lib/index.js:7169:29)
    at Parser.pp$9.jsxParseElement (./node_modules/babylon/lib/index.js:7224:15)
    at Parser.parseExprAtom (./node_modules/babylon/lib/index.js:7236:21)
    at Parser.pp$3.parseExprSubscripts (./node_modules/babylon/lib/index.js:3494:19)
```

**Comment by chrischen** [comment]
Hmm. I think I re-ran installation and got `^7.0.0-bridge.0` added and it works now.
