### ISSUE TITLE
Unable to Extract React + Typescript (with or without eject)

### ISSUE THREAD

**Issue by davidpenn** [lingui/js-lingui#483]
**Describe the bug**
``lingui extract`` throws an error "Unknown option"

**To Reproduce**
```sh
$ npx create-react-app lingui-test --typescript
$ cd lingui-test/
$ yarn add @lingui/core @lingui/macro @lingui/react @types/lingui__core @types/lingui__macro @types/lingui__react @lingui/cli
$ yarn lingui add-locale en
$ yarn lingui extract
```

```
yarn run v1.15.2
$ /Users/david/lingui-test/node_modules/.bin/lingui extract
/Users/david/lingui-test/node_modules/@lingui/cli/api/compat.js:56
        throw e;
        ^

ReferenceError: [BABEL] /Users/david/lingui-test/src/App.test.tsx: Unknown option: /Users/david/lingui-test/node_modules/babel-preset-react-app/index.js.overrides. Check out http://babeljs.io/docs/usage/options/ for more information about options.

A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

Invalid:
  `{ presets: [{option: value}] }`
Valid:
  `{ presets: [['presetName', {option: value}]] }`

For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options. (While processing preset: "/Users/david/lingui-test/node_modules/babel-preset-react-app/index.js")
    at Logger.error (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/logger.js:41:11)
    at OptionManager.mergeOptions (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
    at /Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
    at /Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
    at OptionManager.mergePresets (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
    at OptionManager.mergeOptions (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
    at OptionManager.init (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/Users/david/lingui-test/node_modules/babel-core/lib/transformation/file/index.js:212:65)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Expected behavior**
No error

**Additional context**

- jsLingui version ``2.7.4``
- Babel version 
```
├─ babel-core@6.26.3
└─ react-scripts@2.1.8
   └─ babel-core@7.0.0-bridge.0
```

**Comment by olessavluk** [comment]
Upgrading `react-scripts` to `v3` solved this issue
(guess this ticket can be closed)

**Comment by tricoder42** [comment]
@olessavluk Thanks for the info!

@davidpenn Feel free to post additional info if upgrading react-scripts does fix the problem.
