### ISSUE TITLE
Syntax Error on Plural React Component

### ISSUE THREAD

**Issue by semoal** [lingui/js-lingui#625]
**Describe the bug**
This error happened after running yarn install, all was working correctly.
It's failing on all <Plural> components I have.

```
  Invalid plural rule '=_self'. Must be zero, one, two, few, many, other or exact number depending on your source language ('one' and 'other' for English).
  221 |                   </LabelWithEllipsis>
  222 |                   <Label fontSize={16} color="#243062">
> 223 |                     <Plural
      |                     ^
  224 |                       value={x.total_products}
  225 |                       one="# fund"
  226 |                       other="# funds"
    at File.buildCodeFrameError (x/node_modules/@babel/core/lib/transformation/file/file.js:248:12)
    at PluginPass.buildCodeFrameError (x/node_modules/@babel/core/lib/transformation/plugin-pass.js:43:22)
    at x/node_modules/@lingui/babel-plugin-transform-react/transformer.js:234:26
    at Array.forEach (<anonymous>)
    at Transformer.processElement (x/node_modules/@lingui/babel-plugin-transform-react/transformer.js:232:23)
    at PluginPass.transform (x/node_modules/@lingui/babel-plugin-transform-react/transformer.js:478:24)
    at newFn (x/node_modules/@babel/traverse/lib/visitors.js:179:21)
    at NodePath._call (x/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (x/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (x/node_modules/@babel/traverse/lib/path/context.js:90:31)
```
**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
import { Plural } from "@lingui/react"

export default function App() {
   return <Plural value={resultCount} one="Showing # result" other="Showing # results" />
}
```

**Expected behavior**
Don't explode.

- jsLingui version: 2.9.0
- Babel version `7.9.0`

**Comment by semoal** [comment]
I've fixed it, but i'm not sure why:

In my babel config i have:
```js
    ["@babel/preset-react", {
      development: isDev || isTest,
      useBuiltIns: true,
    }],
    "@lingui/babel-preset-react"
]
```

I've removed development settings to the preset and got fixed. :/

**Comment by N1kto** [comment]
I also had same error. Fixed with replacing `import { Plural } from "@lingui/react"` with `import { Plural } from "@lingui/macro"`
