### ISSUE TITLE
When exported as ES module, use the .mjs file extension

### ISSUE THREAD

**Issue by laszbalo** [lingui/js-lingui#731]
**Is your feature request related to a problem? Please describe.**
For a while node.js natively supporting es modules, but expecting those files to have .mjs extension. At the moment I can set the module format to `es`, but in order to use that, I have to use module bundler.

**Describe proposed solution**
When module format set to `es`, the file extension of the generated files should be `.mjs`.

**Describe alternatives you've considered**
Manually renaming all the generated files after `lingui compile`:
```shell
for f in $(find ./locale/ -type f -name '*.js'); do cp "$f" "${f%.js}.mjs"; done
```

**Comment by tricoder42** [comment]
Hey @laszbalo, this sounds like a good idea. Feel free to send a PR and use `next` branch as a base 👍

**Comment by laszbalo** [comment]
Hi,

I tried adding this, but after half an hour of trying, I was not even be able to run the tests  :(

```shell
$ npm i
$ npm test // -> most of the tests are failing
```

For the time being I will just stick to the above one-liner to rename the message files. I might revisit this later, when I have more time.

P.S. Actually I have never worked with Typescript before. Should I have had Typscript in my class path?

**Comment by tricoder42** [comment]
Not sure if `npm` can handle `yarn` workspaces. Could you please try to install dependencies using `yarn`? If there're still errors, could you please post them here? Thanks 👍

**Comment by laszbalo** [comment]
```shell
$ yarn
$ yarn watch   // then pressed 'a' to run all the tests
```

One snapshot test is failing:

```shell
 FAIL  packages/cli/src/api/formats/po.test.ts
  ● pofile format › should write catalog in pofile format

    expect(received).toMatchSnapshot()

    Snapshot name: `pofile format should write catalog in pofile format 1`

    - Snapshot  - 1
    + Received  + 1

    @@ -1,8 +1,8 @@
      msgid ""
      msgstr ""
    - "POT-Creation-Date: 2018-08-27 10:00+0000\n"
    + "POT-Creation-Date: 2018-08-27 11:00+0100\n"
      "Mime-Version: 1.0\n"
      "Content-Type: text/plain; charset=utf-8\n"
      "Content-Transfer-Encoding: 8bit\n"
      "X-Generator: @lingui/cli\n"
      "Language: en\n"

      71 |     const pofile = fs.readFileSync(filename).toString()
      72 |     mockFs.restore()
    > 73 |     expect(pofile).toMatchSnapshot()
         |                    ^
      74 |   })
      75 | 
      76 |   it("should read catalog in pofile format", function () {

      at Object.<anonymous> (packages/cli/src/api/formats/po.test.ts:73:20)

```

Also, got warning like this:

```shell
    console.warn                                                                                                                                                                                                                                              
      Messages for locale "en" not loaded.                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                              
      139 |     if (process.env.NODE_ENV !== "production") {                                                                                                                                                                                                  
      140 |       if (!this._messages[locale]) {                                                                                                                                                                                                              
    > 141 |         console.warn(`Messages for locale "${locale}" not loaded.`)                                                                                                                                                                               
          |                 ^                                                                                                                                                                                                                                 
      142 |       }                                                                                                                                                                                                                                           
      143 |                                                                                                                                                                                                                                                   
      144 |       if (!this._localeData[locale]) {                                                                                                                                                                                                            
                                      
      at I18n.activate (packages/core/src/i18n.ts:141:17)
      at new I18n (packages/core/src/i18n.ts:64:12)                       
      at setupI18n (packages/core/src/i18n.ts:201:16)
      at Object.<anonymous> (packages/core/src/i18n.test.ts:212:20)
                   
    console.warn
      Locale data for locale "en" not loaded. Plurals won't work correctly.
                   
      143 |    
      144 |       if (!this._localeData[locale]) {
    > 145 |         console.warn(                 
          |                 ^
      146 |           `Locale data for locale "${locale}" not loaded. Plurals won't work correctly.`
      147 |         )
      148 |       }

      at I18n.activate (packages/core/src/i18n.ts:145:17)
      at new I18n (packages/core/src/i18n.ts:64:12)
      at setupI18n (packages/core/src/i18n.ts:201:16)
      at Object.<anonymous> (packages/core/src/i18n.test.ts:212:20)
```


Interestingly, when I run the tests in normal mode with `yarn test`, all the snapshot tests pass. My timezone is British Summer Time, so if I run the tests in watch mode with the time zone set to UTC, `TZ=UTC yarn watch`, all the tests pass.

Should not all the npm scripts which run tests have the TZ environment variable set to UTC?

**Comment by laszbalo** [comment]
Also,

it does not come up as a failed test, but I got this error message on the console:
```shell
    console.error                                                                        
      Warning: An update to I18nProvider inside a test was not wrapped in act(...).                 
                                                                                         
      When testing, code that causes React state updates should be wrapped into act(...):
                                                                                    
      act(() => {                                                                                   
        /* fire events that update state */                               
      });                                                                                           
      /* assert on the output */                                            
                                                                                           
      This ensures that you're testing the behavior the user would see in the browser. Learn more at https://fb.me/react-wrap-tests-with-act
          in I18nProvider                                                                  
                                                                                                                                            
      35 |    */                                                                                    
      36 |   React.useEffect(() => {                                                                
    > 37 |     const unsubscribe = props.i18n.on("change", () => setContext(makeContext()))         
         |                                                       ^                                  
      38 |     return () => unsubscribe()                                                           
      39 |   }, [])                                                                      
      40 |                                                                               
                                                                                         
      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:88:30)                   
      at error (node_modules/react-dom/cjs/react-dom.development.js:60:5)           
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:23284:7)
      at setContext (node_modules/react-dom/cjs/react-dom.development.js:15656:9)
      at I18n.apply (packages/react/src/I18nProvider.tsx:37:55)                                            
      at map (packages/core/src/eventEmitter.ts:25:52)                           
          at Array.map (<anonymous>)                                                                
      at I18n.emit (packages/core/src/eventEmitter.ts:25:25)   
```

**Comment by tricoder42** [comment]
Yes, exactly. The problem was missing `TZ` env var in `watch` command. I've just pushed fixed `package.json` to `next` branch, along with other changes. Could you please `git pull` latest changes and `yarn` install new dependencies? Then try to run `yarn watch` again and it should work.

**Comment by laszbalo** [comment]
That's great. Thanks. Did the change, working on adding tests to `Catalog.writeCompiled()`. Since it's almost five o'clock, probably sending it tomorrow 😉
