### ISSUE TITLE
Not able to upgrade from 2.8.3 to 2.9.2 - lingui extract blocks on jsx

### ISSUE THREAD

**Issue by dysticus** [lingui/js-lingui#738]
**Describe the bug**
Let me start by saying that I possibly have an error in my own code somewhere, but after a lot of searching and debugging, I can't seem to find it. I'm in the middle of the process of upgrading the packages in our package.json. For LinguiJS this means upgrading from 2.8.3 to 2.9.2. Whereas the command `lingui extract` runs smoothly in a previous version, it now stops with the following error:

```SyntaxError: path/to/some/file.js: Unexpected token (14:12)
  12 |   const show = () => {
  13 |     Modal.info({
> 14 |       icon: <Icon name='cog' />,
     |             ^
  15 |       title: i18n._(t`Settings`),
  16 |       content: (
  17 |         <div>
    at Parser.pp$5.raise (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:4454:13)
    at Parser.pp.unexpected AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:1761:8)
    at Parser.pp$3.parseExprAtom (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3750:12)
    at Parser.pp$3.parseExprSubscripts (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3494:19)
    at Parser.pp$3.parseMaybeUnary (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3474:19)
    at Parser.pp$3.parseExprOps (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3404:19)
    at Parser.pp$3.parseMaybeConditional (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3381:19)
    at Parser.pp$3.parseMaybeAssign (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:3344:19)
    at Parser.pp$3.parseObjectProperty (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:4115:99)
    at Parser.pp$3.parseObjPropValue (AppData\Roaming\npm\node_modules\lingui-cli\node_modules\babylon\lib\index.js:4140:84) {
  pos: 434,
  loc: Position { line: 14, column: 12 },
  _babel: true,
  codeFrame: '  12 |   const show= () => {\n' +
    '  13 |     Modal.info({\n' +
    "> 14 |       icon: <Icon name='cog' />,\n" +
    '     |             ^\n' +
    '  15 |       title: i18n._(t`Settings`),\n' +
    '  16 |       content: (\n' +
    '  17 |         <div>'
}
```

**To Reproduce**
Steps to reproduce the behavior, possibly with minimal code sample, e.g:

```
$ npx lingui extract
```

**Expected behavior**

**Additional context**

- jsLingui version ``lingui --version`` 
This outputs 1.4.5 (which is kinda strange no?)
- Babel version ``npm list @babel/core`` 
7.11.6
- Your Babel config (e.g. `.babelrc`) or framework you use (Create React App, Meteor, etc.)
No specific framework, but instead of .babelrc file, I have babel.config.js because I have an isTest Boolean check in it:
```
const isTest = process.env.NODE_ENV === 'test'

module.exports = api => {
  api.cache.using(() => process.env.NODE_ENV)

  return {
    comments: false,
    presets: [
      [
        '@babel/preset-env',
        {
          targets: {
            ie: '11'
          }
        }
      ],
      '@babel/preset-react',
      '@babel/preset-flow',
      '@lingui/babel-preset-js',
      '@lingui/babel-preset-react'
    ],
    plugins: [
      '@babel/plugin-syntax-dynamic-import',
      '@babel/plugin-proposal-class-properties',
      'relay',
      'macros',
      'babel-plugin-idx',
      !isTest && [
        'import',
        {
          'libraryName': 'antd',
          'libraryDirectory': 'es',
          'style': true
        }
      ]
    ].filter(Boolean) // this will filter any falsy plugins (such as removing react-remove-properties when not in production)
  }
}
```
If you need anymore information, let me know.
Thanks already!

**Comment by dysticus** [comment]
As I expected, it was something on my configuration. After clearing npm cache, removing node_modules and reinstalling everything, it started working.
