### ISSUE TITLE
compilation is not working with 3.3.0

### ISSUE THREAD

**Issue by seeden** [lingui/js-lingui#920]
**Describe the bug**
I see compilation issues when I try to compile my code.

```sh
ERROR in ./src/models/User.ts
Module build failed (from ../../node_modules/babel-loader/lib/index.js):
TypeError: /Users/seeden/Documents/git/creolify/packages/api/src/models/User.ts: @lingui/macro: Cannot read property 'findIndex' of undefined Learn more: https://www.npmjs.com/package/@lingui/macro
    at MacroJs.processDescriptor (/Users/seeden/Documents/git/creolify/node_modules/@lingui/macro/macroJs.js:152:73)
    at MacroJs.replaceTAsFunction (/Users/seeden/Documents/git/creolify/node_modules/@lingui/macro/macroJs.js:143:30)
    at MacroJs.replacePath (/Users/seeden/Documents/git/creolify/node_modules/@lingui/macro/macroJs.js:110:15)
    at /Users/seeden/Documents/git/creolify/node_modules/@lingui/macro/index.js:82:11
    at Array.forEach (<anonymous>)
    at macro (/Users/seeden/Documents/git/creolify/node_modules/@lingui/macro/index.js:77:39)
    at macroWrapper (/Users/seeden/Documents/git/creolify/node_modules/babel-plugin-macros/dist/index.js:57:12)
    at applyMacros (/Users/seeden/Documents/git/creolify/node_modules/babel-plugin-macros/dist/index.js:225:14)
    at ImportDeclaration (/Users/seeden/Documents/git/creolify/node_modules/babel-plugin-macros/dist/index.js:109:28)
    at NodePath._call (/Users/seeden/Documents/git/creolify/node_modules/@babel/traverse/lib/path/context.js:55:20)
 @ ./src/models/index.ts 4:0-26 13:2-6
 @ ./src/index.ts 8:0-30 20:41-47
```

I fixed it with
```js
      var messageIndex = descriptor.properties ? descriptor.properties.findIndex(function (property) {
        return property.key.name === _constants.MESSAGE;
      }) : -1;
```

**To Reproduce**
```js
import { t } from "@lingui/macro";

t({
  id: 'test',
  message: 'My translation',
});
```

**Expected behavior**
Compile without errors

- jsLingui version ``3.3.0``

```js
const LOOSE = false;

module.exports = function babel(api) {
  api.cache(true);

  return {
    presets: [
      ['@babel/env', {
        targets: {
          node: '12',
        },
        corejs: 3,
        useBuiltIns: 'entry',
        loose: LOOSE,
      }],
      '@babel/typescript',
      '@babel/react',
    ],
    plugins: [
      '@babel/plugin-proposal-export-default-from',
      ['@babel/plugin-proposal-class-properties', { loose: LOOSE }],
      '@babel/plugin-transform-flow-strip-types',
      'import-graphql',
      'macros',
    ],
  };
};

```

**Comment by tricoder42** [comment]
Interesting. Could you please send a PR and add a test case which covers this usecase?

**Comment by semoal** [comment]
Or at least give us a sample repo to reproduce? I see that @babel/env is used where is deprecated that name, you should use `@babel/preset-env`

**Comment by seeden** [comment]
I will try to reproduce it today and use preset- prefix

**Comment by semoal** [comment]
Hello @seeden can i help you with your issue?, remind to give us a minimal setup for debuggin' your issue

**Comment by mschipperheyn** [comment]
I have had the same issue and it was caused by "old" style @lingui `i18n._(t('id')`Message`)` 2.x references still existing in the code.

**Comment by JSteunou** [comment]
@semoal I think you can re-open this ticket or maybe it is better if I open a new one, you tell me, but I can reproduce this issue if I use `MessageDescriptor` as the documentation says

```js
const predefined = defineMessage({
   message: "foo bar"
})
```

This does not work and triggered the `findIndex` error

```js
t(predefined)
```

This does work

```js
i18n._(predefine)
```

**Comment by jd1378** [comment]
I have the same issue as JSteunou, this is still relevant

**Comment by semoal** [comment]
t macro never worked with message decriptors, if the docs show that we have to change it. 

If your issue is different to that please open another issue with a reproduction repo

**Comment by jd1378** [comment]
okay then, thanks for the info
yeah [the docs](https://lingui.js.org/ref/macro.html) show it like this:
```
t({
   id: "msg.refresh",
   message: "Refresh inbox"
})
``
